### ISSUE TITLE
MultiQC works strangely on Windows

### ISSUE THREAD

**Issue by CPTPaso** [MultiQC/MultiQC#1600]
Hi,

I fetched MultiQC with 
```bash
curl -LOk https://github.com/ewels/MultiQC/archive/master.zip
tar -xf master.zip
cd MultiQC-master
pip install .
```

Via `where multiqc` I could also identify where the exe file is located. 

`C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\Scripts\multiqc.exe <example_fastqc_folder> ` writes the multiqc report into the current working directory. I would like to redirect the output to a directory of my choice. However, specifying an --outdir does not work and gives the error

```python
Traceback (most recent call last):
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\Scripts\multiqc.exe\__main__.py", line 4, in <module>
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\site-packages\multiqc\__main__.py", line 53, in <module>
    multiqc.run_cli(prog_name="multiqc")
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\site-packages\multiqc\multiqc.py", line 249, in run_cli
    multiqc_run = run(
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\site-packages\multiqc\multiqc.py", line 922, in run
    logger.info("Report      : {}".format(os.path.relpath(config.output_fn)))
  File "C:\Users\me\anaconda3\envs\NGS_DGE_pipeline\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'E:', start on mount 'C:'
```
Using Linux, MultiQC works fine. However, I explicitly need to get it running under Windows.
What am I doing wrong? Thanks for your help!

**Comment by ewels** [comment]
So this error is coming from a stdlib function `relpath` in the `os` module. A bit of googling suggests that (a) windows handles paths in a weird way and that (b) if you run MultiQC from the same drive that your log files are in, it should work (as the error message suggests in fact). Could you try that please?

It looks like other tools (eg. Sphinx) have patches this by just catching the `ValueError` and skipping the function call if it is encountered. Which is not ideal, but I could also do I guess.

Phil

**Comment by ewels** [comment]
Closing for now as we have a workaround (run MultiQC on the same drive as your files when using Windows).

If this is confirmed as the problem / fix, and others are still hitting this problem then we can reopen. I guess the solution is to patch every instance of `os.path.relpath` in MultiQC to handle the exception. I'd prefer to avoid this if possible, but it is doable if it's a problem.

**Comment by ewels** [comment]
From Gitter:

> _Finding an odd situation with the multiqc.py use of `os.path.relpath()`. Where used, it does not specify a start directory as the second parameter. As a result, it is causing an exception in the `os.path.ntpath` internal code. The `os.path.relpath()` requires the path and start both be on the same physical device / drive._
> _Maybe my use case is odd, but I am calling `multiqc.run()` from within python. And specifying a search directory and output directory to `multiqc.run()` where the fastq files and reports are to be located. `multiqc.run(outdir.FP, module=['fastqc'], outdir=outdir.FP)` Basically just trying to get a merged report for paired end FASTQs from WGS tests. The code runs on MacOS, Linux and Windows; but we discovered this during regression testing on Windows._
> _Key is the specified search and output directories are on a different disk than the location of the python interpreter, my python scripts, and the installed multiqc python library. When a start directory is not specified as the 2nd parameter to os.path.relpath, their code defaults to the CWD. Which, when called from within python, is where the python module is located. os.path considers it an internal exception to ask for a relative path to a start path that is not on the same device. This is mostly an issue when using python on MS Windows / NT systems where devices have different drive letters. But also occurs when specifying a network filesystem path on *nix servers. For now, I have had to remove the use of `os.path.relpath()` in the multiqc.py code (8 places). Am guessing you likely should have a cluse to a better starting location that is "nearby" and maybe specify it in the call. If you cannot, you should likely not use the call._

**Comment by ewels** [comment]
This should be fixed now. MultiQC no longer calls `os.path.relpath` anywhere in the codebase, so the cross-drive `ValueError` on Windows no longer occurs. Windows is also covered by CI. Closing.
