### ISSUE TITLE
No single plot after clicking on a sample track in "Per Base Sequence Content"

### ISSUE THREAD

**Issue by drhanhluong** [MultiQC/MultiQC#1693]
### Description of bug

I used MultiQC v1.12 and found that the FastQC single plot in " Per Base Sequence Content" could not be loaded.
![Picture1](https://user-images.githubusercontent.com/42739804/170844823-5ff8e32a-db9b-4fb8-a19d-18abdd256152.png)

### MultiQC Error log

```console
multiqc .

  /// MultiQC 🔍 | v1.12

|           multiqc | Search path : /home/hanh/Desktop/Research_KI_project/scRNAdata/raw_read_QC
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 503/503  
|            snippy | Found 1 reports
|          bargraph | Tried to make bar plot, but had no data: snippy_variants
|            fastqc | Found 162 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
|           multiqc | 7 flat-image plots used in the report due to large sample numbers
|           multiqc | To force interactive plots, use the '--interactive' flag. 
See the documentation.
```

**Comment by ewels** [comment]
Is it possible to attach the report to this issue please? (You can zip it to avoid complaints about the file extension).

**Comment by drhanhluong** [comment]
Thank you,
The attached file is the report. Actually I already tried with a subset of
data (20 fastq files), re-installed the multiqc but the problem could not
be solved.
Best regards,
Hanh

**Comment by ewels** [comment]
I don't think that you can attach files to GitHub issues via email sorry, you need to use the web interface.

**Comment by drhanhluong** [comment]
> I don't think that you can attach files to GitHub issues via email sorry, you need to use the web interface.
Thank you. Here the file.
[multiqc_report.zip](https://github.com/ewels/MultiQC/files/8792920/multiqc_report.zip)

**Comment by ewels** [comment]
Many thanks for this. As I suspected, the error is not to do with the _"Per Base Sequence Content"_ plot - that's just where you see the effect. The problem is that the JavaScript in the report hits an error and crashes. You can see in your screenshot that it still says _"Loading report.."_ at the top which is a giveaway for this, and any subsequent JS execution will fail - including clicking on a series in the _"Per Base Sequence Content"_ plot.

The real culprit can be found hiding in the browser console:

<details>

```js
multiqc_report.html:1175 jQuery.Deferred exception: Illegal constructor TypeError: Illegal constructor
    at HTMLDocument.<anonymous> (file:///Users/ewels/Downloads/multiqc_report.html:1346:21)
    at e (file:///Users/ewels/Downloads/multiqc_report.html:1175:29861)
    at t (file:///Users/ewels/Downloads/multiqc_report.html:1175:30185) undefined
C.Deferred.exceptionHook @ multiqc_report.html:1175

multiqc_report.html:1175 Uncaught TypeError: Illegal constructor
    at HTMLDocument.<anonymous> (multiqc_report.html:1346:21)
    at e (multiqc_report.html:1175:29861)
    at t (multiqc_report.html:1175:30185)
highcharts.src.js:219 Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=heatmap
 - missingModuleFor: heatmap
    at Object.<anonymous> (highcharts.src.js:219:35)
    at z (highcharts.src.js:1661:17)
    at f (highcharts.src.js:241:13)
    at a.initSeries (highcharts.src.js:30493:21)
    at highcharts.src.js:32166:21
    at Array.forEach (<anonymous>)
    at a.firstRender (highcharts.src.js:32163:17)
    at a.<anonymous> (highcharts.src.js:30475:21)
    at z (highcharts.src.js:1661:17)
    at a.init (highcharts.src.js:30349:17)

multiqc_report.html:5559 Uncaught TypeError: Cannot read properties of undefined (reading 'buttons')
    at plot_single_seqcontent (multiqc_report.html:5559:52)
    at HTMLCanvasElement.<anonymous> (multiqc_report.html:5381:7)
    at HTMLCanvasElement.dispatch (multiqc_report.html:1175:42846)
    at HTMLCanvasElement.h.handle (multiqc_report.html:1175:40832)
```

</details>

I'm not completely sure what's causing this, but my guess is that it's the _Status Checks_ heat map right at the bottom of the plot.

Before I dig into this any more, could you please send me the verbose log from MultiQC? (`multiqc_data/multiqc.log` or run with `-v`). If you could also send one or two FastQC zip files that trigger the same error so that I can try to replicate the issue at my end that would also be very helpful.

Thanks,

Phil

**Comment by drhanhluong** [comment]
Thank you, Phil.
I send you here the multiqc.log and FastQC zip files. Hope these help.
Hanh
[SRR11260853_1_fastqc.zip](https://github.com/ewels/MultiQC/files/8796791/SRR11260853_1_fastqc.zip)
[SRR11260853_2_fastqc.zip](https://github.com/ewels/MultiQC/files/8796796/SRR11260853_2_fastqc.zip)

[multiqc.zip](https://github.com/ewels/MultiQC/files/8796788/multiqc.zip)

**Comment by araboapresyan** [comment]
I have the same problem with  MultiQC v1.12. No single plot for  " Per Base Sequence Content" and "Status Checks" plot. 
multiqc.log
[multiqc.log](https://github.com/ewels/MultiQC/files/9371843/multiqc.log)

multiqc_report
[multiqc_report.zip](https://github.com/ewels/MultiQC/files/9371897/multiqc_report.zip)

**Comment by ewels** [comment]
This should be fixed now. The traceback was coming from HighCharts, which is completely gone since the Plotly rewrite (#2409).

Closing now, if anything similar comes up again please open a new issue 🙏🏻
