### ISSUE TITLE
Jinja2: bump minimum version

### ISSUE THREAD

**Issue by danarte** [MultiQC/MultiQC#1748]
### Description of bug

I'm trying to use multiqc to look at fastqc reports.
multiqc throws an error and I'm not sure if it's an installation problem / input file problem / or a bug.
Couldn't find related problems on the internet.
I tried with an old preinstalled version (1.8) as well as a new version (1.12) freshly installed with pip, got the same error.

### File that triggers the error

[ERR479405_fastqc.zip](https://github.com/ewels/MultiQC/files/9372840/ERR479405_fastqc.zip)

Added one of the fastqc reports.

### MultiQC Error log

```console
(Multiqc) [user@compute-0-2 workingDir]$ multiqc fastq
[WARNING]         multiqc : MultiQC Version v1.12 now available!
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /genomicslab/nobackup/volume2/user/cancerMicrobiomeDataset/workingDir/fastq
[INFO   ]          fastqc : Found 2 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Previous MultiQC output found! Adjusting filenames..
[WARNING]         multiqc : Use -f or --force to overwrite existing reports instead
[INFO   ]         multiqc : Report      : multiqc_report_3.html
[INFO   ]         multiqc : Data        : multiqc_data_3
Traceback (most recent call last):
  File "/powerapps/share/centos7/miniconda/miniconda3-4.7.12-environmentally/envs/Multiqc/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/multiqc/__main__.py", line 44, in <module>
    multiqc.run_cli(prog_name='multiqc')
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/multiqc/multiqc.py", line 238, in run_cli
    kwargs=kwargs
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/multiqc/multiqc.py", line 808, in run
    report_output = j_template.render(report=report, config=config)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/tmp/tmp9i42cm8v/head.html", line 27, in template
    } | tojson
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/environment.py", line 986, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/tmp/tmp9i42cm8v/base.html", line 27, in top-level template code
    {% include 'head.html' %}
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/tmp/tmp9i42cm8v/head.html", line 27, in template
    } | tojson
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/environment.py", line 515, in _generate
    return generate(source, self, name, filename, defer_init=defer_init)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/compiler.py", line 62, in generate
    generator.visit(node)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/compiler.py", line 816, in visit_Template
    self.blockvisit(node.body, frame)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/compiler.py", line 492, in blockvisit
    self.visit(node, frame)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/compiler.py", line 1353, in visit_Output
    self.visit(argument, frame)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/compiler.py", line 1565, in visit_Filter
    self.fail('no filter named %r' % node.name, node.lineno)
  File "/groups/nshomron/user/.local/lib/python3.6/site-packages/jinja2/compiler.py", line 427, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: no filter named 'tojson'
```

**Comment by ewels** [comment]
I'm pretty sure that this is due to you running an outdated version of `jinja2`

I'm already pinning a minimum version but maybe that's not high enough. Could you please find out what version you have currently then try updating and see if it fixes it?

Something like this: (off the top of my head on my phone, so apologies if there are errors)

```bash
pip freeze | grep jinja
pip install --upgrade --force-reinstall jinja2
```

**Comment by danarte** [comment]
On the older multiqc version the Jinja was Jinja2==2.11.1

I did  a fresh install with a new conda environment and multiqc worked without errors on the same input files. So there was probably some package conflict when I installed it on a "general" conda env. (the jinja version here is Jinja2==3.1.2)

So if someone having the same error, try installing multiqc on a new conda env if possible.

**Comment by ewels** [comment]
Ok great that you got it working! I think I have 2.9 set as the minimum version currently but I see no reason not to increase this. Version 3 has been around for ages now.

**Comment by ewels** [comment]
We bumped the minimum Jinja2 to `>=3.0.0` in MultiQC/MultiQC@73b2397, v1.14.  Thanks all!
