### ISSUE TITLE
Problem with docker usage

### ISSUE THREAD

**Issue by valentinelsra** [MultiQC/MultiQC#2150]
### Description of bug

Hi,

I am trying to run the docker multiqc on my fastqc files with the latest version of multiqc.
It creates the folder multiqc_data but I can not find the html report and I obtain an error, please take a look on the error log below.

Any suggestion ?

Thank you,
Valentine

### File that triggers the error

[C1A_R1_fastqc.zip](https://github.com/ewels/MultiQC/files/13165530/C1A_R1_fastqc.zip)

### MultiQC Error log

```console
$docker run -t --name test_multiqc2 --rm -v ./fastqc/:/home/docker/ -w /home/docker/ ewels/multiqc multiqc .

  /// MultiQC 🔍 | v1.17

|           multiqc | Search path : /home/docker
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 18/18  
|            fastqc | Found 9 reports
|           multiqc | Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
|           multiqc | Report      : multiqc_report_1.html
|           multiqc | Data        : multiqc_data_1
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 8, in <module>
    sys.exit(run_multiqc())
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multiqc/__main__.py", line 23, in run_multiqc
    multiqc.run_cli(prog_name="multiqc")
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 298, in run_cli
    multiqc_run = run(**kwargs)
                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 1014, in run
    shutil.copytree(
  File "/usr/local/lib/python3.11/shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/shutil.py", line 515, in _copytree
    raise Error(errors)
shutil.Error: [('/tmp/tmp035qlzj0/multiqc_data', '/home/docker/multiqc_data_1', '[Errno 1] Operation not permitted')]
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by tamuanand** [comment]
Have you tried this as shown in the first line of traceback

```
Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
```

**Comment by MACBucay** [comment]
How did you solve this issue?
