### ISSUE TITLE
Degenerate flowcell causes bclconvert module to crash

### ISSUE THREAD

**Issue by alanhoyle** [MultiQC/MultiQC#2290]
### Description of bug

We automate our demux runs and use the MultiQC report as the first reference to see how things went.  A recent flowcell was run that generated several hundred completely empty fastqs.  When we run MultiQC on the RunFolder, the `bclconvert` module breaks as it can't calculate mean_quality.  

Three files are required:  Demultiplex_Stats.csv  Quality_Metrics.csv  RunInfo.xml  I have put them in the .ZIP file.  

### File that triggers the error

[test.zip](https://github.com/MultiQC/MultiQC/files/14169678/test.zip)

### MultiQC Error log

```console
time singularity run --bind /datastore docker://multiqc/multiqc:latest     multiqc . -o /tmp     --force --verbose     --ignore Analysis     --module bclconvert  -v
INFO:    Using cached SIF image

  /// MultiQC 🔍 | v1.19

[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  This is MultiQC v1.19
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Command used: /usr/local/bin/multiqc . -o /tmp --force --verbose --ignore Analysis --module bclconvert -v
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Latest MultiQC version is v1.19
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Working dir : /[....CENSORED....]/
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Template    : default
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Running Python 3.11.7 (main, Dec  5 2023, 19:05:17) [GCC 12.2.0]
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Ignoring files, directories and paths that match: Analysis
[2024-02-05 13:18:41] multiqc                                            [INFO   ]  Only using modules: bclconvert
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Analysing modules: bclconvert
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Using temporary directory for creating report: /datastore/scratch/users/clinic_svc/tmpozsf6ow5
[2024-02-05 13:18:41] multiqc                                            [INFO   ]  Search path : /[....CENSORED....]
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Ignored 310 search patterns as didn't match running modules.
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 13/13
[2024-02-05 13:18:41] multiqc                                            [DEBUG  ]  Summary of files that were skipped by the search: [skipped_no_match: 5]
[2024-02-05 13:18:43] multiqc.plots.bargraph                             [DEBUG  ]  Using matplotlib version 3.8.2
[2024-02-05 13:18:43] multiqc.modules.bclconvert.bclconvert              [WARNING]  Found multiple runs from the same sequencer output
[2024-02-05 13:18:43] multiqc.modules.bclconvert.bclconvert              [DEBUG  ]  Determined genome size as: None
[2024-02-05 13:18:43] multiqc.modules.bclconvert.bclconvert              [INFO   ]  2 lanes and 189 samples found
╭────────────────────────────────────── Oops! The 'bclconvert' MultiQC module broke... ──────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                              │
│ Please attach a file that triggers the error. The last file found was: ./test/Quality_Metrics.csv                          │
│                                                                                                                            │
│ Traceback (most recent call last):                                                                                         │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 729, in run                                      │
│     output = mod()                                                                                                         │
│              ^^^^^                                                                                                         │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/bclconvert/bclconvert.py", line 115, in __init__           │
│     plot=self.sample_stats_table(bclconvert_data, bclconvert_by_sample),                                                   │
│          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                    │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/bclconvert/bclconvert.py", line 582, in sample_stats_table │
│     "mean_quality": sample["mean_quality"],                                                                                │
│                     ~~~~~~^^^^^^^^^^^^^^^^                                                                                 │
│ KeyError: 'mean_quality'                                                                                                   │
│                                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[2024-02-05 13:18:43] multiqc                                            [DEBUG  ]  Oops! The 'bclconvert' MultiQC module broke...
================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 729, in run
    output = mod()
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/multiqc/modules/bclconvert/bclconvert.py", line 115, in __init__
    plot=self.sample_stats_table(bclconvert_data, bclconvert_by_sample),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multiqc/modules/bclconvert/bclconvert.py", line 582, in sample_stats_table
    "mean_quality": sample["mean_quality"],
                    ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'mean_quality'
================================================================================
[2024-02-05 13:18:43] multiqc.utils.software_versions                    [DEBUG  ]  Reading software versions from config.software_versions
[2024-02-05 13:18:43] multiqc                                            [WARNING]  No analysis results found. Cleaning up..
[2024-02-05 13:18:43] multiqc                                            [INFO   ]  MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for reporting the issue! It happened because all samples in the test example had zero yield, so the mean quality was not calculated. I added a line now to handle this special case without crashing the module: https://github.com/MultiQC/MultiQC/pull/2297
