### ISSUE TITLE
dragen_fastqc module breaks after plotly error

### ISSUE THREAD

**Issue by jamigo** [MultiQC/MultiQC#2323]
### Description of bug

When dealing with fastqc_metrics.csv files, MultiQC v1.20 is not able to handle an "autorangeoptions" call and plotly dies, breaking the dragen_fastqc module.

Note: when pasting the whole MultiQC log, an error message from GitHub is triggered by the length of the comment. I've removed the "valid properties" list as non informative.

### File that triggers the error

[test.fastqc_metrics.csv](https://github.com/MultiQC/MultiQC/files/14257662/test.fastqc_metrics.csv)

### MultiQC Error log

```console
$ multiqc test.fastqc_metrics.csv

  /// MultiQC 🔍 | v1.20

|           multiqc | Search path : /mnt/netapp2/Store_JAL/temp/multiqc/fastqc_metrics/test.fastqc_metrics.csv
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
╭─────────────────────────────────────────── Oops! The 'dragen_fastqc' MultiQC module broke... ────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                          │
│ Please attach a file that triggers the error. The last file found was: ./test.fastqc_metrics.csv                                         │
│                                                                                                                                          │
│ Traceback (most recent call last):                                                                                                       │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/multiqc/multiqc.py", line 712, in run                                  │
│     output = mod()                                                                                                                       │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/multiqc/modules/dragen_fastqc/dragen_fastqc.py", line 84, in __init__  │
│     samples_found |= self.add_base_metrics()                                                                                             │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/multiqc/modules/dragen_fastqc/base_metrics.py", line 21, in add_base_m │
│     self.positional_mean_quality_plot()                                                                                                  │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/multiqc/modules/dragen_fastqc/base_metrics.py", line 106, in positiona │
│     plot=linegraph.plot(data, pconfig),                                                                                                  │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/multiqc/plots/linegraph.py", line 224, in plot                         │
│     return line.plot(plotdata, pconfig)                                                                                                  │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/multiqc/plots/plotly/line.py", line 34, in plot                        │
│     p = LinePlot(pconfig, lists_of_lines)                                                                                                │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/multiqc/plots/plotly/line.py", line 167, in __init__                   │
│     layout = go.Layout(self.layout.to_plotly_json()).update(**dataset.layout)                                                            │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/plotly/basedatatypes.py", line 5139, in update                         │
│     BaseFigure._perform_update(self, kwargs, overwrite=overwrite)                                                                        │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/plotly/basedatatypes.py", line 3918, in _perform_update                │
│     BaseFigure._perform_update(plotly_obj[key], val)                                                                                     │
│   File "/mnt/netapp2/Store_JAL/.local/lib/python3.9/site-packages/plotly/basedatatypes.py", line 3895, in _perform_update                │
│     raise err                                                                                                                            │
│ ValueError: Invalid property specified for object of type plotly.graph_objs.layout.XAxis: 'autorangeoptions'                             │
│                                                                                                                                          │
│ Did you mean "autorange"?                                                                                                                │
│                                                                                                                                          │
│     Valid properties:     

(here goes a list of valid properties)
                                                                                                               ││                                                                                                                                          │
│ Did you mean "autorange"?                                                                                                                │
│                                                                                                                                          │
│ Bad property path:                                                                                                                       │
│ autorangeoptions                                                                                                                         │
│ ^^^^^^^^^^^^^^^^                                                                                                                         │
│                                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks @jamigo, and sorry for this issue!

Looks like it has to do with the version of Plotly: `autorangeoptions` was added relatively recently, in version 5.17 on [2023-09-15](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#5170---2023-09-15). If you upgrade the version with `pip install plotly --upgrade`, it should resolve this problem. 

(I'll pin Plotly in `setup.py` now and add a runtime check into the code)

**Comment by vladsavelyev** [comment]
(Automatically closed, will keep reopen for some time)

**Comment by jamigo** [comment]
Confirmed: updating previous plotly v5.15 to current v5.18 solves this issue. Thank you!
