### ISSUE TITLE
When pconfig=None get KeyError in table_object.py

### ISSUE THREAD

**Issue by elagina-hh** [MultiQC/MultiQC#2329]
### Description of bug

After updating to version 1.20 custom plugins fail due to this Key Error
```
File "/venv/lib/python3.10/site-packages/multiqc_harbinger_plugin-1.1-py3.10.egg/harbinger/modules/tumor_content/tumor_content.py", line 66, in __init__ │
│     plot=table.plot(self.tumor_content_data, _get_table_headers(self.tumor_content_data))                                                                  │
│   File "/venv/lib/python3.10/site-packages/multiqc/plots/table.py", line 34, in plot                                                                       │
│     dt = table_object.DataTable(data, headers, pconfig)                                                                                                    │
│   File "/venv/lib/python3.10/site-packages/multiqc/plots/table_object.py", line 44, in __init__                                                            │
│     self.id = pconfig.pop("id")                                                                                                                            │
│ KeyError: 'id'
```
Error seems to be originating in table_object.py, when pconfig=None (as it is an optional parameter)
https://github.com/MultiQC/MultiQC/blob/6c613e885250ca24dee90025adb5f5a0dbded314/multiqc/plots/table_object.py#L25
https://github.com/MultiQC/MultiQC/blob/6c613e885250ca24dee90025adb5f5a0dbded314/multiqc/plots/table_object.py#L35-L36
but then on this line it tires to access "id"
https://github.com/MultiQC/MultiQC/blob/6c613e885250ca24dee90025adb5f5a0dbded314/multiqc/plots/table_object.py#L44

### MultiQC Error log

```console
multiqc -f --filename multiqc_report . --interactive -m tumor_content
╭──────────────────────────────────────────────────── Oops! The 'tumor_content' MultiQC module broke... ─────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                            │
│ Please attach a file that triggers the error. The last file found was: ./PID_21895.estimate_tumor_content.txt                                              │
│                                                                                                                                                            │
│ Traceback (most recent call last):                                                                                                                         │
│   File "/venv/lib/python3.10/site-packages/multiqc/multiqc.py", line 712, in run                                                                           │
│     output = mod()                                                                                                                                         │
│   File "/venv/lib/python3.10/site-packages/multiqc_harbinger_plugin-1.1-py3.10.egg/harbinger/modules/tumor_content/tumor_content.py", line 66, in __init__ │
│     plot=table.plot(self.tumor_content_data, _get_table_headers(self.tumor_content_data))                                                                  │
│   File "/venv/lib/python3.10/site-packages/multiqc/plots/table.py", line 34, in plot                                                                       │
│     dt = table_object.DataTable(data, headers, pconfig)                                                                                                    │
│   File "/venv/lib/python3.10/site-packages/multiqc/plots/table_object.py", line 44, in __init__                                                            │
│     self.id = pconfig.pop("id")                                                                                                                            │
│ KeyError: 'id'                                                                                                                                             │
│
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry for this and thanks a lot for reporting the issue! Should be fixed with https://github.com/MultiQC/MultiQC/pull/2337
