### ISSUE TITLE
"Failed to start Kaleido subprocess" when calling `full_figure_for_development`

### ISSUE THREAD

**Issue by insilicool** [MultiQC/MultiQC#2357]
### Description of bug

I am currently testing the latest version of Multiqc before a version bump to our production pipelines.  Our current version (1.14) works with our integration tests, however, the GATK4/Picard GCbias summary metrics file is not behaving correctly in the latest version. 

### File that triggers the error

[tumorPair_COLO829.gcbias_summary.tar.gz](https://github.com/MultiQC/MultiQC/files/14347912/tumorPair_COLO829.gcbias_summary.tar.gz)

This file contains 2 GCbias summary files from normal and tumor, plus the full multiqc log file using -v option.

### MultiQC Error log

```console
module purge && \
module load mugqic/MultiQC/1.20 && \
multiqc -f -v  \
metrics/tumorPair_COLO829 \
metrics/tumorPair_COLO829N  \
metrics/tumorPair_COLO829T \
-n report/tumorPair_COLO829.multiqc.html

  /// MultiQC 🔍 | v1.20

[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  This is MultiQC v1.20
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  Command used: /cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/bin/multiqc -f -v metrics/tumorPair_COLO829 metrics/tumorPair_COLO829N metrics/tumorPair_COLO829T -n report/tumorPair_COLO829.multiqc.html
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  Could not connect to multiqc.info for version check: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  Working dir : /lb/project/mugqic/projects/jenkins_tests/GenPipesFull_tumor_dnaseq_merge_2024-02-19T16.02.02/scriptTestOutputs/dnaseq_somatic_fastpass_b38
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  Template    : default
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  Running Python 3.12.2 (main, Feb 12 2024, 11:24:27) [GCC 9.3.0]
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  Analysing modules: custom_content, ccs, ngsderive, purple, conpair, lima, peddy, somalier, methylqa, mosdepth, phantompeakqualtools, qualimap, bamdst, preseq, hifiasm, quast, qorts, rna_seqc, rockhopper, rsem, rseqc, busco, bustools, goleft_indexcov, gffcompare, disambiguate, supernova, deeptools, sargasso, verifybamid, mirtrace, happy, mirtop, sambamba, gopeaks, homer, hops, macs2, theta2, snpeff, gatk, htseq, bcftools, featureCounts, fgbio, dragen, dragen_fastqc, dedup, pbmarkdup, damageprofiler, mapdamage, biobambam2, jcvi, mtnucratio, picard, vep, bakta, prokka, qc3C, nanostat, samblaster, samtools, sexdeterrmine, seqera_cli, eigenstratdatabasetools, bamtools, jellyfish, vcftools, longranger, stacks, varscan2, snippy, umitools, truvari, megahit, bbmap, bismark, biscuit, diamond, hicexplorer, hicup, hicpro, salmon, kallisto, slamdunk, star, hisat2, tophat, bowtie2, bowtie1, cellranger, snpsplit, odgi, pangolin, nextclade, freyja, humid, kat, leehom, librarian, nonpareil, adapterRemoval, bbduk, clipandmerge, cutadapt, flexbar, sourmash, kaiju, bracken, kraken, malt, motus, trimmomatic, sickle, skewer, sortmerna, biobloomtools, fastq_screen, afterqc, fastp, fastqc, filtlong, prinseqplusplus, pychopper, porechop, pycoqc, minionqc, anglerfish, multivcfanalyzer, clusterflow, checkqc, bcl2fastq, bclconvert, interop, ivar, flash, seqyclean, optitype, whatshap, xenome, xengsort, metaphlan, seqwho
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  Using temporary directory for creating report: /tmp/tmph20g486a
[2024-02-20 09:09:44] multiqc                                            [INFO   ]  Search path : /lb/project/mugqic/projects/jenkins_tests/GenPipesFull_tumor_dnaseq_merge_2024-02-19T16.02.02/scriptTestOutputs/dnaseq_somatic_fastpass_b38/metrics/tumorPair_COLO829
[2024-02-20 09:09:44] multiqc                                            [INFO   ]  Search path : /lb/project/mugqic/projects/jenkins_tests/GenPipesFull_tumor_dnaseq_merge_2024-02-19T16.02.02/scriptTestOutputs/dnaseq_somatic_fastpass_b38/metrics/tumorPair_COLO829N
[2024-02-20 09:09:44] multiqc                                            [INFO   ]  Search path : /lb/project/mugqic/projects/jenkins_tests/GenPipesFull_tumor_dnaseq_merge_2024-02-19T16.02.02/scriptTestOutputs/dnaseq_somatic_fastpass_b38/metrics/tumorPair_COLO829T
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 48/48
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  Summary of files that were skipped by the search: [skipped_module_specific_max_filesize: 98] // [skipped_no_match: 24] // [skipped_ignore_pattern: 14] // [skipped_filesize_limit: 2]
[2024-02-20 09:09:44] multiqc                                            [DEBUG  ]  No samples found: custom_content
[2024-02-20 09:09:44] multiqc.modules.conpair.conpair                    [DEBUG  ]  Duplicate sample name found! Overwriting: tumorPair_COLO829T
[2024-02-20 09:09:44] multiqc.modules.conpair.conpair                    [INFO   ]  Found 1 reports
[2024-02-20 09:09:44] multiqc.utils.util_functions                       [DEBUG  ]  Wrote data file multiqc_conpair.txt
[2024-02-20 09:09:44] multiqc.modules.mosdepth.mosdepth                  [INFO   ]  Found reports for 2 samples
[2024-02-20 09:09:44] multiqc.utils.util_functions                       [DEBUG  ]  Wrote data file mosdepth_cumcov_dist.txt
[2024-02-20 09:09:44] multiqc.utils.util_functions                       [DEBUG  ]  Wrote data file mosdepth_cov_dist.txt
[2024-02-20 09:09:44] multiqc.utils.util_functions                       [DEBUG  ]  Wrote data file mosdepth_perchrom.txt
[2024-02-20 09:09:44] multiqc.modules.mosdepth.mosdepth                  [DEBUG  ]  Using default coverage thresholds: 1, 5, 10, 30, 50
[2024-02-20 09:09:45] multiqc.utils.util_functions                       [DEBUG  ]  Wrote data file multiqc_picard_AlignmentSummaryMetrics.txt
[2024-02-20 09:09:45] multiqc.modules.picard.picard                      [INFO   ]  Found 2 AlignmentSummaryMetrics reports
[2024-02-20 09:09:45] multiqc.modules.picard.BaseDistributionByCycleMetrics [DEBUG  ]  Duplicate sample name found in tumorPair_COLO829N.all.metrics.base_distribution_by_cycle_metrics! Overwriting: tumorPair_COLO829N_R1
[2024-02-20 09:09:45] multiqc.modules.picard.BaseDistributionByCycleMetrics [DEBUG  ]  Duplicate sample name found in tumorPair_COLO829N.all.metrics.base_distribution_by_cycle_metrics! Overwriting: tumorPair_COLO829N_R2
[2024-02-20 09:09:45] multiqc.modules.picard.BaseDistributionByCycleMetrics [DEBUG  ]  Duplicate sample name found in tumorPair_COLO829T.all.metrics.base_distribution_by_cycle_metrics! Overwriting: tumorPair_COLO829T_R1
[2024-02-20 09:09:45] multiqc.modules.picard.BaseDistributionByCycleMetrics [DEBUG  ]  Duplicate sample name found in tumorPair_COLO829T.all.metrics.base_distribution_by_cycle_metrics! Overwriting: tumorPair_COLO829T_R2
[2024-02-20 09:09:45] multiqc.utils.util_functions                       [DEBUG  ]  Wrote data file multiqc_picard_baseContent.txt
[2024-02-20 09:09:45] multiqc.modules.picard.picard                      [INFO   ]  Found 4 BaseDistributionByCycleMetrics reports
╭──────────────────────────────────────────────────────────── Oops! The 'picard' MultiQC module broke... ────────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                    │
│ Please attach a file that triggers the error. The last file found was: metrics/tumorPair_COLO829T/tumorPair_COLO829T.all.metrics.gcbias_summary_metrics.txt        │
│                                                                                                                                                                    │
│ Traceback (most recent call last):                                                                                                                                 │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/multiqc/multiqc.py", line 712, in run                                │
│     output = mod()                                                                                                                                                 │
│              ^^^^^                                                                                                                                                 │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/multiqc/modules/picard/picard.py", line 90, in __init__              │
│     n[tool] = func(self)                                                                                                                                           │
│               ^^^^^^^^^^                                                                                                                                           │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/multiqc/modules/picard/GcBiasMetrics.py", line 135, in parse_reports │
│     plot=linegraph.plot(data_by_sample, pconfig),                                                                                                                  │
│          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                   │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/multiqc/plots/linegraph.py", line 224, in plot                       │
│     return line.plot(plotdata, pconfig)                                                                                                                            │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                            │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/multiqc/plots/plotly/line.py", line 34, in plot                      │
│     p = LinePlot(pconfig, lists_of_lines)                                                                                                                          │
│         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                          │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/multiqc/plots/plotly/line.py", line 168, in __init__                 │
│     dev_fig = dataset.create_figure(layout).full_figure_for_development(warn=False)                                                                                │
│               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/plotly/basedatatypes.py", line 3472, in full_figure_for_development  │
│     return pio.full_figure_for_development(self, warn, as_dict)                                                                                                    │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                    │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/plotly/io/_kaleido.py", line 344, in full_figure_for_development     │
│     fig = json.loads(scope.transform(fig, format="json").decode("utf-8"))                                                                                          │
│                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/kaleido/scopes/plotly.py", line 153, in transform                    │
│     response = self._perform_transform(                                                                                                                            │
│                ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                            │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/kaleido/scopes/base.py", line 293, in _perform_transform             │
│     self._ensure_kaleido()                                                                                                                                         │
│   File "/cvmfs/soft.mugqic/CentOS6/software/MultiQC/MultiQC-1.20/lib/python3.12/site-packages/kaleido/scopes/base.py", line 198, in _ensure_kaleido                │
│     raise ValueError(message)                                                                                                                                      │
│ ValueError: Failed to start Kaleido subprocess. Error stream:                                                                                                      │
│                                                                                                                                                                    │
│ [0220/090945.144736:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale                                                                           │
│ --type=zygote: error while loading shared libraries: --type=zygote: cannot open shared object file                                                                 │
│ --type=zygote: error while loading shared libraries: --type=zygote: cannot open shared object file                                                                 │
│ [0220/090945.465496:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 1 time(s)                                                                       │
│ --type=utility: error while loading shared libraries: --type=utility: cannot open shared object file                                                               │
│ [0220/090945.477813:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 2 time(s)                                                                       │
│ [0220/090945.478512:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 3 time(s)                                                                       │
│ [0220/090945.479137:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 4 time(s)                                                                       │
│ [0220/090945.481950:ERROR:network_service_instance_impl.cc(286)] Network service crashed, restarting service.                                                      │
│ [0220/090945.483976:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 5 time(s)                                                                       │
│ --type=utility: error while loading shared libraries: --type=utility: cannot open shared object file                                                               │
│ [0220/090945.486213:ERROR:network_service_instance_impl.cc(286)] Network service crashed, restarting service.                                                      │
│ [0220/090945.487918:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 6 time(s)                                                                       │
│ --type=utility: error while loading shared libraries: --type=utility: cannot open shared object file                                                               │
│ [0220/090945.487952:FATAL:gpu_data_manager_impl_private.cc(407)] GPU process isn't usable. Goodbye.                                                                │
│ #0 0x7f4cf0e4dd79 base::debug::CollectStackTrace()                                                                                                                 │
│ #1 0x7f4cf0dcb633 base::debug::StackTrace::StackTrace()                                                                                                            │
│ #2 0x7f4cf0ddb15f logging::LogMessage::~LogMessage()                                                                                                               │
│ #3 0x7f4cef937907 content::(anonymous namespace)::IntentionallyCrashBrowserForUnusableGpuProcess()                                                                 │
│ #4 0x7f4cef9356be content::GpuDataManagerImplPrivate::FallBackToNextGpuMode()                                                                                      │
│ #5 0x7f4cef933c53 content::GpuDataManagerImpl::FallBackToNextGpuMode()                                                                                             │
│ #6 0x7f4cef93df5f content::GpuProcessHost::RecordProcessCrash()                                                                                                    │
│ #7 0x7f4cef7c86d3 content::BrowserChildProcessHostImpl::OnProcessLaunchFailed()                                                                                    │
│ #8 0x7f4cef8281f0 content::internal::ChildProcessLauncherHelper::PostLaunchOnClientThread()                                                                        │
│ #9 0x7f4cef828435 base::internal::Invoker<>::RunOnce()                                                                                                             │
│ #10 0x7f4cf0e11306 base::TaskAnnotator::RunTask()                                                                                                                  │
│ #11 0x7f4cf0e22cf6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()                                                             │
│ #12 0x7f4cf0e229ea base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()                                                                 │
│ #13 0x7f4cf0e6f899 base::MessagePumpLibevent::Run()                                                                                                                │
│ #14 0x7f4cf0e2359b base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()                                                                    │
│ #15 0x7f4cf0dfc9bd base::RunLoop::Run()                                                                                                                            │
│ #16 0x7f4cef7e4f18 content::BrowserProcessSubThread::IOThreadRun()                                                                                                 │
│ #17 0x7f4cf0e3b874 base::Thread::ThreadMain()                                                                                                                      │
│ #18 0x7f4cf0e5dcaa base::(anonymous namespace)::ThreadFunc()                                                                                                       │
│ #19 0x7f4cec003609 start_thread                                                                                                                                    │
│ #20 0x7f4cebbc3103 clone                                                                                                                                           │
│ Task trace:                                                                                                                                                        │
│ #0 0x7f4cef82805e content::internal::ChildProcessLauncherHelper::PostLaunchOnLauncherThread()                                                                      │
│ #1 0x7f4cef827afc content::internal::ChildProcessLauncherHelper::StartLaunchOnClientThread()                                                                       │
│ #2 0x7f4cefd597c2 content::VizProcessTransportFactory::ConnectHostFrameSinkManager()                                                                               │
│ #3 0x7f4cf147d26f mojo::SimpleWatcher::Context::Notify()                                                                                                           │
│ #4 0x7f4cefd597c2 content::VizProcessTransportFactory::ConnectHostFrameSinkManager()                                                                               │
│ Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.                                                                                 │
│                                                                                                                                                                    │
│ Received signal 6                                                                                                                                                  │
│ #0 0x7f4cf0e4dd79 base::debug::CollectStackTrace()                                                                                                                 │
│ #1 0x7f4cf0dcb633 base::debug::StackTrace::StackTrace()                                                                                                            │
│ #2 0x7f4cf0e4d95b base::debug::(anonymous namespace)::StackDumpSignalHandler()                                                                                     │
│ #3 0x7f4cec00f3c0 (/cvmfs/soft.mugqic/apt/ubuntu2004/1.0/lib/x86_64-linux-gnu/libpthread-2.31.so+0x153bf)                                                          │
│ #4 0x7f4cebae718b gsignal                                                                                                                                          │
│ #5 0x7f4cebac6859 abort                                                                                                                                            │
│ #6 0x7f4cf0e4c8f5 base::debug::BreakDebugger()                                                                                                                     │
│ #7 0x7f4cf0ddb5b2 logging::LogMessage::~LogMessage()                                                                                                               │
│ #8 0x7f4cef937907 content::(anonymous namespace)::IntentionallyCrashBrowserForUnusableGpuProcess()                                                                 │
│ #9 0x7f4cef9356be content::GpuDataManagerImplPrivate::FallBackToNextGpuMode()                                                                                      │
│ #10 0x7f4cef933c53 content::GpuDataManagerImpl::FallBackToNextGpuMode()                                                                                            │
│ #11 0x7f4cef93df5f content::GpuProcessHost::RecordProcessCrash()                                                                                                   │
│ #12 0x7f4cef7c86d3 content::BrowserChildProcessHostImpl::OnProcessLaunchFailed()                                                                                   │
│ #13 0x7f4cef8281f0 content::internal::ChildProcessLauncherHelper::PostLaunchOnClientThread()                                                                       │
│ #14 0x7f4cef828435 base::internal::Invoker<>::RunOnce()                                                                                                            │
│ #15 0x7f4cf0e11306 base::TaskAnnotator::RunTask()                                                                                                                  │
│ #16 0x7f4cf0e22cf6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()                                                             │
│ #17 0x7f4cf0e229ea base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()                                                                 │
│ #18 0x7f4cf0e6f899 base::MessagePumpLibevent::Run()                                                                                                                │
│ #19 0x7f4cf0e2359b base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()                                                                    │
│ #20 0x7f4cf0dfc9bd base::RunLoop::Run()                                                                                                                            │
│ #21 0x7f4cef7e4f18 content::BrowserProcessSubThread::IOThreadRun()                                                                                                 │
│ #22 0x7f4cf0e3b874 base::Thread::ThreadMain()                                                                                                                      │
│ #23 0x7f4cf0e5dcaa base::(anonymous namespace)::ThreadFunc()                                                                                                       │
│ #24 0x7f4cec003609 start_thread                                                                                                                                    │
│ #25 0x7f4cebbc3103 clone                                                                                                                                           │
│   r8: 0000000000000000  r9: 00007f4cccebe2a0 r10: 0000000000000008 r11: 0000000000000246                                                                           │
│  r12: 00007f4cccebed40 r13: 00007f4cccebf5a0 r14: 00007f4cccebf5b0 r15: 00007f4cccebf5b8                                                                           │
│   di: 0000000000000002  si: 00007f4cccebe2a0  bp: 00007f4cccebe4f0  bx: 00007f4cccec0700                                                                           │
│   dx: 0000000000000000  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007f4cccebe2a0                                                                           │
│   ip: 00007f4cebae718b efl: 0000000000000246 cgf: 0000000000000033 erf: 0000000000000000                                                                           │
│  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000                                                                                                 │
│ [end of stack trace]                                                                                                                                               │
│ Calling _exit(1). Core file will not be generated.                                                                                                                 │
│                                                                                                                                                                    │
│                                                                                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[2024-02-20 09:09:45] multiqc                                            [DEBUG  ]  Oops! The 'picard' MultiQC module broke...
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
According to the logs, it looks like there is a more general problem - the Kaleido package is failing. 

This PR should fix this: https://github.com/MultiQC/MultiQC/pull/2359

<hr>

But note that your `*gcbias_summary_metrics.txt` files shouldn't result in any plots anyway - the GcBias submodule only plots the _detail_ GcBias metrics, those that contain:

```
## METRICS CLASS        picard.analysis.GcBiasDetailMetrics
ACCUMULATION_LEVEL      READS_USED      GC      WINDOWS READ_STARTS     MEAN_BASE_QUALITY       NORMALIZED_COVERAGE     ERROR_BAR_WIDTH SAMPLE  LIBRARY READ_GROUP
All Reads       ALL     0       133376  83      23      0.080694        0.008857
All Reads       ALL     1       95527   46      23      0.062441        0.009206
All Reads       ALL     2       110295  92      22      0.108161        0.011277
All Reads       ALL     3       140901  146     22      0.134363        0.01112
...
```

Vs. the summary metrics that just contain two data lines:

```
## METRICS CLASS        picard.analysis.GcBiasSummaryMetrics
ACCUMULATION_LEVEL      READS_USED      WINDOW_SIZE     TOTAL_CLUSTERS  ALIGNED_READS   AT_DROPOUT      GC_DROPOUT      GC_NC_0_19      GC_NC_20_39     GC_NC_40_59     GC_NC_60_79     GC_NC_80_100    SAMPLE  LIBRARY READ_GROUP
All Reads       ALL     100     8073762 16115914        1.02996 0.685728        1.142765        1.042615        0.973322        1.043185        0.971094
All Reads       UNIQUE  100     7214872 14407002        1.004983        0.593189        1.136803        1.032233        0.975687        1.048801        0.973339
```

Let me know if it makes sense to add any visualisation for summary as well?
