### ISSUE TITLE
PURPLE: missing `version` column in v4.0.1

### ISSUE THREAD

**Issue by insilicool** [MultiQC/MultiQC#2363]
### Description of bug

After you fixed my initial issue (https://github.com/MultiQC/MultiQC/issues/2357) I did a pull of your dev branch and reran MultiQC.  This time PURPLE seems to be giving the issue.  It should be noted that I did a bump of the PURPLE version from 3.7.1 to 4.0.1, so perhaps there was a change to the outputs from PURPLE.

### File that triggers the error

[tumorPair_COLO829T.purple.purity.tar.gz](https://github.com/MultiQC/MultiQC/files/14364402/tumorPair_COLO829T.purple.purity.tar.gz)

Contain the tumorPair_COLO829T.purple.purity.tsv file and multiqc log

### MultiQC Error log

```console
multiqc -f -v \
metrics/tumorPair_COLO829  \
metrics/tumorPair_COLO829N \
metrics/tumorPair_COLO829T \
-n report/tumorPair_COLO829.multiqc.html

  /// MultiQC 🔍 | v1.21.dev0

|           multiqc | Search path : /lb/project/mugqic/projects/jenkins_tests/GenPipesFull_tumor_dnaseq_merge_2024-02-20T16.37.52/scriptTestOutputs/dnaseq_somatic_ensemble_b38/metrics/tumorPair_COLO829
|           multiqc | Search path : /lb/project/mugqic/projects/jenkins_tests/GenPipesFull_tumor_dnaseq_merge_2024-02-20T16.37.52/scriptTestOutputs/dnaseq_somatic_ensemble_b38/metrics/tumorPair_COLO829N
|           multiqc | Search path : /lb/project/mugqic/projects/jenkins_tests/GenPipesFull_tumor_dnaseq_merge_2024-02-20T16.37.52/scriptTestOutputs/dnaseq_somatic_ensemble_b38/metrics/tumorPair_COLO829T
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 50/50
╭────────────────────────────────────────────────────── Oops! The 'purple' MultiQC module broke... ───────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                         │
│ Please attach a file that triggers the error. The last file found was: metrics/tumorPair_COLO829/tumorPair_COLO829T.purple.purity.tsv                   │
│                                                                                                                                                         │
│ Traceback (most recent call last):                                                                                                                      │
│   File "/lb/project/mugqic/analyste_dev/software/MultiQC/1.21_rjme/lib/python3.12/site-packages/multiqc/multiqc.py", line 720, in run                   │
│     output = mod()                                                                                                                                      │
│              ^^^^^                                                                                                                                      │
│   File "/lb/project/mugqic/analyste_dev/software/MultiQC/1.21_rjme/lib/python3.12/site-packages/multiqc/modules/purple/purple.py", line 49, in __init__ │
│     self.add_software_version(data["version"], f["s_name"])                                                                                             │
│                               ~~~~^^^^^^^^^^^                                                                                                           │
│ KeyError: 'version'                                                                                                                                     │
│                                                                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           conpair | Found 1 reports
|          mosdepth | Found reports for 2 samples
|            picard | Found 2 AlignmentSummaryMetrics reports
|            picard | Found 4 BaseDistributionByCycleMetrics reports
|            picard | Found 2 GcBiasMetrics reports
|            picard | Found 2 InsertSizeMetrics reports
|            picard | Found 2 MarkDuplicates reports
|            picard | Found 2 OxoGMetrics reports
|            picard | Found 2 QualityByCycleMetrics reports
|            picard | Found 2 QualityScoreDistributionMetrics reports
|             fastp | Found 2 reports
|           multiqc | Report      : report/tumorPair_COLO829.multiqc.html   (overwritten)
|           multiqc | Data        : report/tumorPair_COLO829.multiqc_data   (overwritten)
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks @insilicool for the bug report!

It looks like the Purple output doesn't include the `version` column, which is weird. Looks like it's something after this change: https://github.com/hartwigmedical/hmftools/commit/e22f6b86c1dfcdaa89599022e0d29ece54b6772a#diff-ad74628e0ce7447317bf1540955f0e15c89ff2ba79d5a5b994b535da485c0c27R178, though it still looks like `version` should be reported. Could you create an [issue at hmftools](https://github.com/hartwigmedical/hmftools/issues) about the missing version column?

In the meantime, I made MultiQC robust to the missing version field, so at least it shouldn't crash anymore 😅 https://github.com/MultiQC/MultiQC/pull/2366
