### ISSUE TITLE
Object of type function is not JSON serializable

### ISSUE THREAD

**Issue by fgvieira** [MultiQC/MultiQC#2437]
### Description of bug

When parsing the `nonpareil` output, I get an error about `TypeError: Object of type function is not JSON serializable`.

Not sure if related to #1509.

### File that triggers the error

[example.json](https://github.com/MultiQC/MultiQC/files/14560504/example.json)

### MultiQC Error log

```console
$ multiqc .
  /// MultiQC 🔍 | v1.21

|           multiqc | Search path : examples/robot_tests/XX
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
|         nonpareil | Found 1 reports
|            violin | All values are NaN or Inf for metric: Mb Ideal seq. effort
|            violin | All values are NaN or Inf for metric: Model correlation
Traceback (most recent call last):
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/bin/multiqc", line 10, in <module>
    sys.exit(run_multiqc())
             ^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/site-packages/multiqc/__main__.py", line 23, in run_multiqc
    multiqc.run_cli(prog_name="multiqc")
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/site-packages/multiqc/multiqc.py", line 299, in run_cli
    multiqc_run = run(**kwargs)
                  ^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/site-packages/multiqc/multiqc.py", line 991, in run
    report.plot_compressed_json = report.compress_json(report.plot_data)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/site-packages/multiqc/utils/report.py", line 572, in compress_json
    json_string = json.dumps(data).encode("utf-8", "ignore").decode("utf-8")
                  ^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "conda/8d0cdfb8373015f96a1ef8f9b3305f1a_/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this issue!

A `"modify"` lambda function from a table column description crept into the JSON dump. We usually remove lambdas after applying them to tables as needed, but here it didn't happen because of an edge-case bug: no non-nan values were found for `nonpareil_LRstar` and a loop exited early.

Fixed now https://github.com/MultiQC/MultiQC/pull/2455

The whole JSON serialization thing will be refactored properly with Pydantic soon https://github.com/MultiQC/MultiQC/pull/2442 to prevent such errors early.
