### ISSUE TITLE
Version 1.21 not working with bbmap test data

### ISSUE THREAD

**Issue by erinyoung** [MultiQC/MultiQC#2480]
### Description of bug

I installed multiqc with pip and cloned MultiQC_TestData into a gitpod instance. I ran multiqc version 1.21 on the MultiQC_TestData directory and this did not finish due to errors. I think there may be something wrong the the `bbmap` module.

My command history:
```
git clone https://github.com/ewels/MultiQC_TestData
pip install multiqc
multiqc MultiQC_TestData/
```

### File that triggers the error

MultiQC_TestData repository (https://github.com/ewels/MultiQC_TestData)

```
git clone https://github.com/ewels/MultiQC_TestData
```

### MultiQC Error log

```console
$ multiqc MultiQC_TestData/

  /// MultiQC 🔍 | v1.21

|           multiqc | Search path : /workspace/docker-builds/MultiQC_TestData
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2720/2720  
|    custom_content | No data found in test_html_mqc.yaml
|    custom_content | download_links: Found 1 samples (table)
|    custom_content | general_stats: Found 4 General Statistics columns
|    custom_content | custom-html: Found 1 sample (html)
|    custom_content | tools-html: Found 1 sample (html)
|    custom_content | ngi-rnaseq: Found 1 sample (html)
|    custom_content | table_headers: Found 1 samples (table)
|    custom_content | custom_data_json_table: Found 1 samples (table)
|    custom_content | custom_data_yaml_table: Found 1 samples (table)
|    custom_content | custom_bargraph_tsv: Found 1 samples (bargraph)
|    custom_content | custom_data_lineplot: Found 1 samples (linegraph)
|    custom_content | mqc_pca: Found 1 samples (scatter)
|    custom_content | custom_data_scatter: Found 1 samples (scatter)
|    custom_content | test_table: Found 1 samples (table)
|    custom_content | Test-Mire2: Found 1 sample (image)
|    custom_content | dupRadar_plot: Found 1 sample (image)
|    custom_content | some_science: Found 1 sample (image)
|    custom_content | mqc_pca2: Found 3 samples (scatter)
|    custom_content | ivar_variants: Found 1 samples (bargraph)
|    custom_content | bargraph_multiple_samples: Found 1 samples (bargraph)
|    custom_content | sample_1: Found 1 samples (linegraph)
|    custom_content | sample_2: Found 1 samples (linegraph)
|    custom_content | sample_3: Found 1 samples (linegraph)
|    custom_content | sample_4: Found 1 samples (linegraph)
|    custom_content | big_heatmap: Found 32 samples (heatmap)
|    custom_content | heatmap_example: Found 4 samples (heatmap)
|    custom_content | issue_1091: Found 1 samples (table)
|    custom_content | linegraph_multiple_samples: Found 1 samples (linegraph)
|    custom_content | my_test: Found 1 sample (html)
|    custom_content | no_header: Found 1 samples (bargraph)
|    custom_content | table_data: Found 1 samples (table)
|    custom_content | summary_assembly_metrics: Found 1 samples (table)
|    custom_content | summary_variants_metrics: Found 1 samples (bargraph)
|               ccs | Found 2 reports
|         ngsderive | Found 2 reports
|            purple | Found 4 reports
|           conpair | Found 3 reports
|            isoseq | Found 2 cluster reports
|            isoseq | Found 3 refine reports
|            isoseq | Found 3 refine reports
|              lima | Found 2 reports
|              lima | Found 27 samples
|             peddy | Found 8 reports
|          somalier | Found 2026 reports
|          methylqa | Found 2 reports
|          mosdepth | Found reports for 7 samples
|phantompeakqualtools | Found 10 logs
|          qualimap | Found 6 BamQC reports
|          qualimap | Found 6 RNASeq reports
|            bamdst | Found 5 reports
|            preseq | Mixed 'TOTAL_READS' and 'TOTAL_BASES' reports. Will build two separate plots
|            preseq | Found 17 reports
|           hifiasm | Found 2 reports
|             quast | Found 12 reports
|             qorts | Found 6 logs
|          rna_seqc | Found 4 samples
|        rockhopper | Found 4 reports
|              rsem | Found 4 reports
|             rseqc | Found 6 read_distribution reports
|gene_body_coverage | Empty geneBodyCoverage file found: empty_failed.geneBodyCoverage.txt
|             rseqc | Found 14 gene_body_coverage reports
|             rseqc | Found 2 inner_distance reports
|             rseqc | Found 1 read_gc reports
|             rseqc | Found 1 read_duplication reports
|             rseqc | Found 1 junction_annotation reports
|junction_saturation | Junction saturation data all zeroes, skipping: 'all_zeroes'
|             rseqc | Found 5 junction_saturation reports
|             rseqc | Found 2 infer_experiment reports
|             rseqc | Found 7 bam_stat reports
|             rseqc | Found 2 tin reports
|             busco | Found 3 reports
|          bustools | Found 1 logs
|   goleft_indexcov | Found 45 samples
|        gffcompare | Found 1 reports
|      disambiguate | Found 3 reports
|         supernova | Found 4 reports
|         deeptools | Found 98 total deepTools samples
|          sargasso | Found 1 reports
|       verifybamid | Found 2 reports
|             happy | Found 1 reports
|            mirtop | Found 161 reports
|          sambamba | Found 22 sambamba markdup reports
|           gopeaks | Found 3 samples
|             homer | Found 2 findPeaks reports
|             homer | Found 16 tagDir reports
|              hops | Found 10 samples
|             macs2 | Found 3 logs
|            theta2 | Found 1 reports
|            snpeff | Found 2 reports
|analyze_saturation_mutagenesis | Found 1 AnalyzeSaturationMutagenesis reports
| base_recalibrator | Found 2 BaseRecalibrator reports
|       varianteval | Found 4 VariantEval reports
|             htseq | Found 4 reports
|          bcftools | Found 4 stats reports
|    feature_counts | Found 20 reports
|             fgbio | Found 1 groupreadsbyumi reports
|             fgbio | Found 1 errorratebyreadposition reports
|            dragen | Found samples: 18
|     dragen_fastqc | Found 2 reports
|             dedup | Found 2 reports
|              jcvi | Found 3 logs
|        mtnucratio | Found 1 reports
|            picard | Found 10 AlignmentSummaryMetrics reports
|            picard | Found 4 BaseDistributionByCycleMetrics reports
|            picard | Found 1 CrosscheckFingerprints reports
|            picard | Found 12 GcBiasMetrics reports
|            picard | Found 10 HsMetrics reports
|            picard | Found 14 InsertSizeMetrics reports
|            picard | Found 15 MarkDuplicates reports
|            picard | Found 3 OxoGMetrics reports
|            picard | Found 3 QualityByCycleMetrics reports
|            picard | Found 3 QualityScoreDistributionMetrics reports
|            picard | Found 2 QualityYieldMetrics reports
|            picard | Found 3 RnaSeqMetrics reports
|            picard | Found 1 RrbsSummaryMetrics reports
|            picard | Found 1 TargetedPcrMetrics reports
|            picard | Found 1 VariantCallingMetrics reports
|            picard | Found 5 ValidateSamFile reports
|            picard | Found 5 WgsMetrics reports
|            picard | Found 2 IlluminaBasecallingMetrics reports
|            picard | Found 2 IlluminaLaneMetrics reports
|            picard | Found 3 ExtractIlluminaBarcodes reports
|            picard | Found 8 MarkIlluminaAdapters reports
|               vep | Found 8 VEP summaries
|             bakta | Found 2 logs
|            prokka | Found 2 logs
|              qc3C | Found 34 reports
|          nanostat | Found 9 reports
|        samblaster | Found 5 reports
|          samtools | Found 5 stats reports
|          samtools | Found 4 flagstat reports
|          samtools | Found 3 idxstats reports
|          samtools | Found 2 rmdup reports
|          samtools | Found 3 coverage reports
|        seqera_cli | Found 10 reports
|eigenstratdatabasetools | Found 1 reports
|          bamtools | Found 2 bamtools stats reports
|         jellyfish | Found 2 reports
|      relatedness2 | Found 2 valid relatedness2 matrices
|          vcftools | Found 2 TsTv.count reports
|          vcftools | Found 4 TsTv.qual reports
|          vcftools | Found 3 TsTv.summary reports
|        longranger | Found 3 reports
|            stacks | Found 7 reports
|          varscan2 | Found 3 reports
|            snippy | Found 3 reports
|            snippy | Found 1 snippy-core reports
|          umitools | Found 60 deduplication reports
|          umitools | Found 1 extract reports
|           truvari | Found 7 truvari bench reports
|           megahit | Found 2 reports
|             bbmap | Found 4 reports
╭───────────────────────────────────────────── Oops! The 'bbmap' MultiQC module broke... ──────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                      │
│ Please attach a file that triggers the error. The last file found was: MultiQC_TestData/data/modules/bbmap/sample1/sample1.statsfile │
│                                                                                                                                      │
│ Traceback (most recent call last):                                                                                                   │
│   File "/opt/conda/lib/python3.12/site-packages/multiqc/multiqc.py", line 751, in run                                                │
│     output = mod()                                                                                                                   │
│              ^^^^^                                                                                                                   │
│   File "/opt/conda/lib/python3.12/site-packages/multiqc/modules/bbmap/bbmap.py", line 64, in __init__                                │
│     plot=self.plot(file_type),                                                                                                       │
│          ^^^^^^^^^^^^^^^^^^^^                                                                                                        │
│   File "/opt/conda/lib/python3.12/site-packages/multiqc/modules/bbmap/bbmap.py", line 179, in plot                                   │
│     return plot_func(samples, file_type, plot_title=plot_title, plot_params=plot_params)                                             │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                             │
│   File "/opt/conda/lib/python3.12/site-packages/multiqc/modules/bbmap/plot_qahist.py", line 46, in plot_qahist                       │
│     x: samples[sample]["data"][x][column] if x in samples[sample]["data"] else 0 for x in all_x                                      │
│        ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^                                                                                            │
│ IndexError: list index out of range                                                                                                  │
│                                                                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────��─────────────────────────────────────╯
|           bismark | Found 9 alignment reports
|           bismark | Found 9 dedup reports
|           bismark | Found 9 methextract reports
|           biscuit | Found 4 samples
|           diamond | Found 2 reports
|       hicexplorer | Found 9 reports
|             hicup | Found 13 reports
|            hicpro | Found 6 HiC-Pro reports
|            salmon | Found 2 meta reports
|            salmon | Found 2 fragment length distributions
|            salmon | Found 1 library format counts reports
|          kallisto | Found 26 reports
|          slamdunk | Found 6 reports
|              star | Found 11 reports and 1 gene count files
|            hisat2 | Found 5 reports
|            tophat | Found 3 reports
|           bowtie2 | Found 8 reports
|           bowtie1 | Found 4 reports
|        cellranger | Found 7 Cell Ranger count reports
|        cellranger | Found 1 Cell Ranger VDJ reports
|          snpsplit | Found 10 reports
|              odgi | Found 5 reports
|          pangolin | Found 14 samples
|         nextclade | Found 7 samples
|            freyja | Found 3 reports
|             humid | Found 1 reports
|               kat | Found 4 reports
|            leehom | Found 1 reports
|         librarian | Found 10 samples
|         nonpareil | Found 2 reports
|    adapterRemoval | Found 5 reports
|             bbduk | Found 1 reports
|      clipandmerge | Found 1 reports
|          cutadapt | Found 38 reports
|           flexbar | Found 4 logs
|           compare | Found a 'labels' file expected by Sourmash: 'MultiQC_TestData/data/modules/sourmash/compare/no_matrix.labels.txt', however, could not find a accompanying matrix binary file 'MultiQC_TestData/data/modules/sourmash/compare/no_matrix'. So assuming that wasn't a Sourmash result
|           compare | Found 2 valid compare results
|          sourmash | Found 2 compare results
|          sourmash | Found 2 gather results
|             kaiju | Found 4 reports
|            kraken | Found 1 reports
|            kraken | Found 13 reports
|            kraken | Kraken2 reports of different versions were found
|              malt | Found 71 reports
|             motus | Found 1 reports
|       trimmomatic | Found 7 logs
|            skewer | Found 5 reports
|         sortmerna | Found 2 logs
|     biobloomtools | Found 1 reports
|      fastq_screen | Couldn't find number of reads with no hits for 'LIB014528_GEN00035295_TGACCA_L001_R1_screen'
|      fastq_screen | Couldn't find number of reads with no hits for 'LIB014528_GEN00035295_TGACCA_L001_R2_screen'
|      fastq_screen | Found 13 reports
|      fastq_screen | No counts found for 'No hits' ('LIB014528_GEN00035295_TGACCA_L001_R1_screen'). Could be malformed or very old FastQ Screen results. Skipping sample
|      fastq_screen | No counts found for 'No hits' ('LIB014528_GEN00035295_TGACCA_L001_R2_screen'). Could be malformed or very old FastQ Screen results. Skipping sample
|           afterqc | Could not parse AfterQC JSON: 'broken.fq.gz.json'
|           afterqc | Found 6 reports
|             fastp | Could not parse sample name from the fastp command:
fastp --json HG001.fastp.json --html HG001.fastp.html --report_title HG001 fastp report --thread 16 --detect_adapter_for_pe
Falling back to extracting it from the file name: "bad_command.fastp.json" -> "bad_command"
|             fastp | Found 10 reports
|            fastqc | Couldn't read 'fake_report_fastqc.zip' - Bad zip file
|            fastqc | Found 55 reports
|            fastqc | Sample had zero reads: 'SK-GBD-000919.1'
|          filtlong | Found 3 reports
|   prinseqplusplus | Found 1 reports
|         pychopper | Found 1 reports
|          porechop | Found 2 reports
|            pycoqc | Found 3 reports
|          minionqc | Found 2 reports
|        anglerfish | Found 1 reports
|       clusterflow | Found 4 pipelines
|           checkqc | Found 1 run and 6 samples
|        bclconvert | Found RunInfo.xml file in MultiQC_TestData/data/modules/bclconvert/3.9.3/merged/Reports but no Demux Stats file, skipping
|        bclconvert | Found multiple sequencer runs
|        bclconvert | 12 lanes and 236 samples found
|           interop | Found 3 reports
|              ivar | Found 3 reports
|              ivar | Number of samples and primers do not match: 3 vs 3
|             flash | Found 5 log reports
|             flash | Found 4 histogram reports
|         seqyclean | Found 6 logs
|          optitype | Found 1 reports
|          whatshap | Could not find the 'ALL' chromosome for GM24385_0_1x_full_opt_trunc. Make sure that the input is not truncated. MultiQC will summarize information for all available chromosomes instead.
|       spaceranger | Found 7 Space Ranger count reports
|            xenome | Found 3 reports
|          xengsort | Found 1 reports
|         metaphlan | Found 1 reports
|            seqwho | Found 1 reports
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
This issue was fixed with https://github.com/MultiQC/MultiQC/pull/2411, so it will be a part of the next release. For now, feel free to install from the source if you need to run the module. Sorry for this problem, and thanks for reporting!
