### ISSUE TITLE
Kraken report gives an error

### ISSUE THREAD

**Issue by lskatz** [MultiQC/MultiQC#2497]
### Description of bug

Hi, I am getting no errors so far. But when I add a kraken report file, I get the following error.

```text
(sneakernet) [gzu2@monolith3 MultiQC-build]$ multiqc . --force

  /// MultiQC � | v1.17

|           multiqc | Search path : /scicomp/groups-pure/OID/NCEZID/DFWED/EDLB/projects/ont-pn-validation/AR_Bank-Illumina/shortreads/Campy/SneakerNet/MultiQC-build
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 10/10
|    custom_content | addReadMetrics': Found 10 samples (bargraph)
|    custom_content | sn_mlst': Found 5 samples (table)
|    custom_content | sn_detectContamination-kraken': Found 5 samples (table)
|    custom_content | baseBalance': Found 20 samples (bargraph)
|    custom_content | sn_staramr': Found 5 samples (table)
|    custom_content | sn_passfail': Found 5 samples (table)
|    custom_content | sn_detectContamination-mlst': Found 5 samples (table)
╭──────────────────────────────────────────────── Oops! The 'kraken' MultiQC module broke... ────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                              │
│ Please attach a file that triggers the error. The last file found was: ./foobar.report                                                     │
│                                                                                                                                            │
│ Traceback (most recent call last):                                                                                                         │
│   File "/scicomp/home-pure/gzu2/bin/miniconda3/envs/sneakernet/lib/python3.9/site-packages/multiqc/multiqc.py", line 689, in run           │
│     output = mod()                                                                                                                         │
│   File "/scicomp/home-pure/gzu2/bin/miniconda3/envs/sneakernet/lib/python3.9/site-packages/multiqc/modules/kraken/kraken.py", line 51, in  │
│     for f in self.find_log_files(self.anchor, filehandles=True):                                                                           │
│   File "/scicomp/home-pure/gzu2/bin/miniconda3/envs/sneakernet/lib/python3.9/site-packages/multiqc/modules/base_module.py", line 139, in f │
│     for f in report.files[sp_key]:                                                                                                         │
│ KeyError: 'kraken-1'                                                                                                                       │
│                                                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | Report      : multiqc_report.html   (overwritten)
|           multiqc | Data        : multiqc_data   (overwritten)
|           multiqc | MultiQC complete
```

This is the content of `foobar.report`

```text
  5.00  21431   21431   U       0       unclassified
 95.00  407300  623     -       1       root
 94.86  406677  0       -       131567    cellular organisms
 94.85  406662  5806    D       2           Bacteria
 93.30  399988  249     P       1224          Proteobacteria
 93.17  399430  5       -       68525           delta/epsilon subdivisions
 93.16  399425  0       C       29547             Epsilonproteobacteria
 93.16  399425  696     O       213849              Campylobacterales
 93.00  398712  1045    F       72294                 Campylobacteraceae
 92.72  397503  62770   G       194                     Campylobacter
 71.77  307703  26611   S       197                       Campylobacter jejuni
 65.56  281092  281092  -       32022                       Campylobacter jejuni subsp. jejuni
  4.14  17743   17743   S       195                       Campylobacter coli
```

### File that triggers the error

Sorry to be lazy about the drag/drop on the file. It is above.

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by lskatz** [comment]
Here are all the files: [campy.zip](https://github.com/MultiQC/MultiQC/files/15018814/campy.zip)

**Comment by lskatz** [comment]
Removing `passfail_mqc.tsv` fixes the issue and I'm going to guess because it has `kraken` as a header. Do I just need to not have Kraken as a header anywhere?

**Comment by vladsavelyev** [comment]
Hi @lskatz, this was fixed last year with https://github.com/MultiQC/MultiQC/pull/2170, so there is no error in the most recent release (`multiqc==1.21`). You are using an old version `v1.17`. I wonder if you could install a more recent MultiQC version?

**Comment by lskatz** [comment]
🤦 sorry, yes, updating did fix it. I have no idea why it wasn't the latest version with this fresh install. But also I should have checked.
