### ISSUE TITLE
Failed with cellranger multi

### ISSUE THREAD

**Issue by khoidnyds** [MultiQC/MultiQC#2578]
### Description of bug

I ran multiqc for cellranger multi output and get the error 

### File that triggers the error

[web_summary.html.zip](https://github.com/MultiQC/MultiQC/files/15349383/web_summary.html.zip)

### MultiQC Error log

```console
/// MultiQC 🔍 v1.23.dev0

[2024-05-17 07:15:57,524] multiqc.core.update_config                         [DEBUG  ]  This is MultiQC v1.23.dev0
[2024-05-17 07:15:57,524] multiqc.core.update_config                         [DEBUG  ]  Running Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29)  [GCC 10.4.0]
[2024-05-17 07:15:57,534] urllib3.connectionpool                             [DEBUG  ]  Starting new HTTPS connection (1): api.multiqc.info:443
[2024-05-17 07:16:01,585] multiqc.core.version_check                         [DEBUG  ]  Timed out after waiting for 2s for multiqc.info to check latest version: HTTPSConnectionPool(host='api.multiqc.info', port=443): Max retries exceeded with url: /version?version_multiqc=1.23.dev0&version_python=3.9.15&operating_system=Linux&is_docker=False&is_singularity=False&is_conda=True&is_ci=False&is_notebook=False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x155539efbaf0>, 'Connection to api.multiqc.info timed out. (connect timeout=2)'))
[2024-05-17 07:16:01,586] multiqc.multiqc                                    [DEBUG  ]  Working dir : Lung_scRNAseq
[2024-05-17 07:16:01,586] multiqc.multiqc                                    [DEBUG  ]  Template    : default
[2024-05-17 07:16:01,586] multiqc.multiqc                                    [DEBUG  ]  Command used: mambaforge/envs/rnaseq/bin/multiqc -v -o Lung_scRNAseq/results/cellranger/gex_multi Lung_scRNAseq/results/cellranger/gex_multi/
[2024-05-17 07:16:01,588] multiqc.core.file_search                           [DEBUG  ]  Analysing modules: custom_content, ccs, ngsderive, purple, conpair, isoseq, lima, peddy, somalier, methylqa, mosdepth, phantompeakqualtools, qualimap, bamdst, preseq, hifiasm, quast, qorts, rna_seqc, rockhopper, rsem, rseqc, busco, bustools, goleft_indexcov, gffcompare, disambiguate, supernova, deeptools, sargasso, verifybamid, mirtrace, happy, mirtop, sambamba, gopeaks, homer, hops, macs2, theta2, snpeff, gatk, htseq, bcftools, featureCounts, fgbio, dragen, dragen_fastqc, dedup, pbmarkdup, damageprofiler, mapdamage, biobambam2, jcvi, mtnucratio, picard, vep, bakta, prokka, qc3C, nanostat, samblaster, samtools, sexdeterrmine, seqera_cli, eigenstratdatabasetools, bamtools, jellyfish, vcftools, longranger, stacks, varscan2, snippy, umitools, truvari, megahit, bbmap, bismark, biscuit, diamond, hicexplorer, hicup, hicpro, salmon, kallisto, slamdunk, star, hisat2, tophat, bowtie2, bowtie1, hostile, cellranger, snpsplit, odgi, pangolin, nextclade, freyja, humid, kat, leehom, librarian, nonpareil, adapterremoval, bbduk, clipandmerge, cutadapt, flexbar, sourmash, kaiju, bracken, kraken, malt, motus, trimmomatic, sickle, skewer, sortmerna, biobloomtools, fastq_screen, afterqc, fastp, fastqc, sequali, filtlong, prinseqplusplus, pychopper, porechop, pycoqc, minionqc, anglerfish, multivcfanalyzer, clusterflow, checkqc, bcl2fastq, bclconvert, interop, ivar, flash, seqyclean, optitype, whatshap, spaceranger, xenome, xengsort, metaphlan, seqwho
[2024-05-17 07:16:01,588] multiqc.core.file_search                           [INFO   ]  Search path: Lung_scRNAseq/results/cellranger/gex_multi
[2024-05-17 07:16:01,593] multiqc.report                                     [DEBUG  ]  Ignored 1 search patterns as didn't match running modules.

[2024-05-17 07:32:12,420] multiqc.report                                     [DEBUG  ]  Summary of files that were skipped by the search: |skipped_module_specific_max_filesize: 580079|, |skipped_no_match: 254634|, |skipped_ignore_pattern: 1360|, |skipped_filesize_limit: 745|, |skipped_directory_fn_ignore_dirs: 1|
[2024-05-17 07:32:12,421] multiqc.core.exec_modules                          [DEBUG  ]  Running module: custom_content
[2024-05-17 07:32:12,494] multiqc.core.exec_modules                          [DEBUG  ]  No samples found: custom_content
[2024-05-17 07:32:12,495] multiqc.core.exec_modules                          [DEBUG  ]  Running module: cellranger
[2024-05-17 07:32:12,537] multiqc.modules.cellranger.vdj                     [DEBUG  ]  Duplicate sample name found in web_summary.html! Overwriting: GEX_1N-5GE
[2024-05-17 07:32:12,538] multiqc.modules.cellranger.vdj                     [DEBUG  ]  Duplicate sample name found in web_summary.html! Overwriting: GEX_1N-5GE
╭─────────────── Oops! The 'cellranger' MultiQC module broke... ───────────────╮
│ Please copy this log and report it at                                        │
│ https://github.com/MultiQC/MultiQC/issues                                    │
│ Please attach a file that triggers the error. The last file found was:       │
│ Lung_scRNAseq/results/cellra │
│ nger/gex_multi/1N-5GE/SC_MULTI_CS/SC_MULTI_CORE/MULTI_GEM_WELL_PROCESSOR/VDJ │
│ _B_GEM_WELL_PROCESSOR/PER_SAMPLE_VDJ_ANALYZER/SUMMARIZE_VDJ_REPORTS/fork_GEX │
│ _1N-5GE/files/web_summary.html                                               │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "mambaforge/envs/rnaseq/lib/python3. │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = modul │
│   File "mambaforge/envs/rnaseq/lib/python3. │
│     n["vdj"] = self.parse_vdj_html()                                         │
│   File "mambaforge/envs/rnaseq/lib/python3. │
│     self.parse_vdj_report(f)                                                 │
│   File "mambaforge/envs/rnaseq/lib/python3. │
│     + mydict["summary_tab"]["vdj_enrichment"]["table"]["rows"]               │
│ KeyError: 'vdj_enrichment'                                                   │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
[2024-05-17 07:32:12,615] multiqc.core.exec_modules                          [DEBUG  ]  Oops! The 'cellranger' MultiQC module broke...
================================================================================
Traceback (most recent call last):
  File "mambaforge/envs/rnaseq/lib/python3.9/site-packages/multiqc/core/exec_modules.py", line 70, in exec_modules
    these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()
  File "mambaforge/envs/rnaseq/lib/python3.9/site-packages/multiqc/modules/cellranger/cellranger.py", line 41, in __init__
    n["vdj"] = self.parse_vdj_html()
  File "mambaforge/envs/rnaseq/lib/python3.9/site-packages/multiqc/modules/cellranger/vdj.py", line 31, in parse_vdj_html
    self.parse_vdj_report(f)
  File "mambaforge/envs/rnaseq/lib/python3.9/site-packages/multiqc/modules/cellranger/vdj.py", line 230, in parse_vdj_report
    + mydict["summary_tab"]["vdj_enrichment"]["table"]["rows"]
KeyError: 'vdj_enrichment'
================================================================================
[2024-05-17 07:32:12,616] multiqc.core.software_versions                     [DEBUG  ]  Reading software versions from config.software_versions
[2024-05-17 07:32:12,616] multiqc.core.exec_modules                          [WARNING]  No analysis results found. Cleaning up…
[2024-05-17 07:32:12,616] multiqc.core.exec_modules                          [INFO   ]  MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for sharing the file and sorry about the issue! Fixed with https://github.com/MultiQC/MultiQC/pull/2579
