### ISSUE TITLE
The latest version of multiqc failing on HPC with OSError: [Errno 122] Disk quota exceeded:

### ISSUE THREAD

**Issue by Rohit-Satyam** [MultiQC/MultiQC#2606]
### Description of bug

Hi

I installed multiqc today using conda and I get the following error. The error persists in [v1.22.1](https://github.com/MultiQC/MultiQC/releases/tag/v1.22.1) as well and since I couldn't install the lower versions other than `v1.14`, I can't say if the error persists. Using `v.1.14` the error disappears.

Note: I am using multiqc within a nextflow pipeline, if that's relevant.

### MultiQC Error log

```console
$ multiqc .

/// MultiQC 🔍 v1.22.1

     version_check | MultiQC Version v1.22.2 now available!
       file_search | Search path: /ibex/scratch/projects/c2077/subudhak/Ivermectin/RNAgrinder/R4_NTwt_work/7f/636d18deeb4b18bda35c8114fe76ea
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 12/12  
            fastqc | Found 2 reports
Traceback (most recent call last):
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/bin/multiqc", line 10, in <module>
    sys.exit(run_multiqc())
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/multiqc/__main__.py", line 21, in run_multiqc
    multiqc.run_cli(prog_name="multiqc")
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/multiqc/multiqc.py", line 448, in run_cli
    result = run(*analysis_dir, clean_up=clean_up, cfg=cfg)
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/multiqc/multiqc.py", line 514, in run
    write_results()
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/multiqc/core/write_results.py", line 50, in write_results
    _write_data_files()
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/multiqc/core/write_results.py", line 383, in _write_data_files
    report.data_sources_tofile()
  File "/ibex/scratch/projects/c2077/subudhak/miniconda3/envs/RNAgrinder/lib/python3.9/site-packages/multiqc/report.py", line 699, in data_sources_tofile
    with io.open(os.path.join(config.data_dir, fn), "w", encoding="utf-8") as f:
OSError: [Errno 122] Disk quota exceeded: '/ibex/scratch/projects/c2077/subudhak/Ivermectin/RNAgrinder/R4_NTwt_work/7f/636d18deeb4b18bda35c8114fe76ea/multiqc_data/multiqc_sources.txt'
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [x] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by ewels** [comment]
Hi @Rohit-Satyam 

```
Disk quota exceeded
```

It looks like you ran out of disk space :)

As I don't believe that this is a problem with MultiQC, I'll close the issue. Let me know if there's something I'm missing and I'd be happy to reopen.

Phil

**Comment by Rohit-Satyam** [comment]
@ewels If that was the case `v1.14` shouldn't work either. But it does. For now, I downgraded the multiqc to that version. We have petabytes of space, so it is something with multiqc. You can take your time because I can use a lower version of multiqc until then

```
Filesystem      Size  Used Avail Use% Mounted on
beegfs_nodev    5.8P  3.5P  2.3P  60% /ibex/scratch
```

**Comment by ewels** [comment]
If you can attach some files that replicate the error we can look into it.
