### ISSUE TITLE
error and traceback with dupRadar files from nf-core/rnaseq in 1.22+

### ISSUE THREAD

**Issue by pinin4fjords** [MultiQC/MultiQC#2646]
### Description of bug

nf-core/rnaseq passes *.duprateExpDensCurve_mqc.txt files to multiQC. The latest version (1.22.2) produces an error and traceback like the below. 

Works fine in 1.21.

### File that triggers the error

[foo.zip](https://github.com/user-attachments/files/15928999/foo.zip)

### MultiQC Error log

```console
$ multiqc --force --config multiqc_config.yml .

/// MultiQC 🔍 v1.22.2

            config | Loading config settings from: multiqc_config.yml
            config | Loading config settings from: multiqc_config.yml
       file_search | Only using modules: custom_content, fastqc, cutadapt, fastp, sortmerna, star, hisat2, rsem, salmon, kallisto, samtools, picard, preseq, rseqc, qualimap
       file_search | Search path: /path/to/projects/rnaseq/work/f9/176356f098df7f4cef3b19f2d89c30/foo
            report | Skipping 17 file search patterns
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 4/4  
╭────────────────────────────────────────────────────────── Oops! The 'custom_content' MultiQC module broke... ───────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                         │
│ Please attach a file that triggers the error. The last file found was: 123/RAP1_IAA_30M_REP1_duprateExpDensCurve_mqc.txt                                                │
│                                                                                                                                                                         │
│ Traceback (most recent call last):                                                                                                                                      │
│   File "/path/to/mambaforge/envs/multiqc/lib/python3.11/site-packages/multiqc/core/exec_modules.py", line 70, in exec_modules                            │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                                             │
│                                                                        ^^^^^^^^^^^^^^^^^^^^                                                                             │
│   File "/path/to/mambaforge/envs/multiqc/lib/python3.11/site-packages/multiqc/modules/custom_content/custom_content.py", line 256, in custom_module_clas │
│     parsed_modules[mod_id].add_cc_section(c_id, mod)                                                                                                                    │
│   File "/path/to/mambaforge/envs/multiqc/lib/python3.11/site-packages/multiqc/modules/custom_content/custom_content.py", line 367, in add_cc_section     │
│     plot = linegraph.plot(mod["data"], pconfig=pconfig)                                                                                                                 │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 │
│   File "/path/to/mambaforge/envs/multiqc/lib/python3.11/site-packages/multiqc/plots/linegraph.py", line 40, in plot                                      │
│     pconfig = LinePlotConfig(**pconfig)                                                                                                                                 │
│               ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                 │
│   File "/path/to/mambaforge/envs/multiqc/lib/python3.11/site-packages/multiqc/plots/plotly/plot.py", line 89, in __init__                                │
│     super().__init__(**data)                                                                                                                                            │
│   File "/path/to/mambaforge/envs/multiqc/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__                                           │
│     self.__pydantic_validator__.validate_python(data, self_instance=self)                                                                                               │
│ pydantic_core._pydantic_core.ValidationError: 6 validation errors for LinePlotConfig                                                                                    │
│ x_lines.0.label.float                                                                                                                                                   │
│   Input should be a valid number [type=float_type, input_value={'style': {'color': 'gree...gn': 'bottom', 'y': -65}, input_type=dict]                                   │
│     For further information visit https://errors.pydantic.dev/2.7/v/float_type                                                                                          │
│ x_lines.0.label.int                                                                                                                                                     │
│   Input should be a valid integer [type=int_type, input_value={'style': {'color': 'gree...gn': 'bottom', 'y': -65}, input_type=dict]                                    │
│     For further information visit https://errors.pydantic.dev/2.7/v/int_type                                                                                            │
│ x_lines.0.label.str                                                                                                                                                     │
│   Input should be a valid string [type=string_type, input_value={'style': {'color': 'gree...gn': 'bottom', 'y': -65}, input_type=dict]                                  │
│     For further information visit https://errors.pydantic.dev/2.7/v/string_type                                                                                         │
│ x_lines.1.label.float                                                                                                                                                   │
│   Input should be a valid number [type=float_type, input_value={'style': {'color': 'red'...gn': 'bottom', 'y': -65}, input_type=dict]                                   │
│     For further information visit https://errors.pydantic.dev/2.7/v/float_type                                                                                          │
│ x_lines.1.label.int                                                                                                                                                     │
│   Input should be a valid integer [type=int_type, input_value={'style': {'color': 'red'...gn': 'bottom', 'y': -65}, input_type=dict]                                    │
│     For further information visit https://errors.pydantic.dev/2.7/v/int_type                                                                                            │
│ x_lines.1.label.str                                                                                                                                                     │
│   Input should be a valid string [type=string_type, input_value={'style': {'color': 'red'...gn': 'bottom', 'y': -65}, input_type=dict]                                  │
│     For further information visit https://errors.pydantic.dev/2.7/v/string_type                                                                                         │
│                                                                                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
      exec_modules | No analysis results found. Cleaning up…
      exec_modules | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about that issue, and thanks for reporting! We got more strict with validating the plot configs, but didn't test it well on the nf-core/rnaseq workflow. Added support for the `label` field, which fixes this issue. I added your test example into test-data: https://github.com/MultiQC/test-data/commit/dd76c36b65634e03565caa8d035ac2e82b642317
