### ISSUE TITLE
dump_json method missing required positional argument: 'filehandle' in utils/megaqc.py::multiqc_api_post

### ISSUE THREAD

**Issue by aanil** [MultiQC/MultiQC#2681]
### Description of bug

The method `dump_json` when called in `utils/megaqc.py::multiqc_api_post` throws an exception with the error 
```
multiqc/utils/megaqc.py", line 20, in multiqc_api_post
    post_data = dump_json({"data": exported_data}, ensure_ascii=False, indent=2)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dump_json() missing 1 required positional argument: 'filehandle'
```

### MultiQC Error log

```console
/// MultiQC 🔍 v1.22.3

            config | Loading config settings from: multiqc_config.yml
            config | Loading config settings from: multiqc_sthlm_config.yml
       file_search | Search path: /scratch/nxf.TfNcOIb3Yl
       file_search | Only using modules: custom_content, hisat2, picard, preseq, qualimap, rsem, rseqc, salmon, samtools, sortmerna, star, fastqc, cutadapt, fastqc
            report | Skipping 17 file search patterns

        validation | custom_content/custom_content.py: Warnings in FlatLine plot configuration {'color': 'green', 'dashStyle': 'LongDash', 'label': {'style': {'color': 'green'}, 'text': '0.5 RPKM', 'verticalAlign': 'bottom', 'y': -65}, 'value': 0.5, 'width': 1}:
        validation | • Deprecated field 'dashStyle'. Use 'dash' instead
        validation | • Line plot's x_lines or y_lines 'label' field is expected to be a string. Other fields other than 'text' are deprecated and will be ignored
        validation | custom_content/custom_content.py: Warnings in FlatLine plot configuration {'color': 'red', 'dashStyle': 'LongDash', 'label': {'style': {'color': 'red'}, 'text': '1 read/bp', 'verticalAlign': 'bottom', 'y': -65}, 'value': 1000, 'width': 1}:
        validation | • Deprecated field 'dashStyle'. Use 'dash' instead
        validation | • Line plot's x_lines or y_lines 'label' field is expected to be a string. Other fields other than 'text' are deprecated and will be ignored
        validation | custom_content/custom_content.py: Warnings in LinePlot plot configuration {'title': 'DupRadar General Linear Model', 'xLog': True, 'xlab': 'expression (reads/kbp)', 'ylab': '% duplicate reads', 'ymax': 100, 'ymin': 0, 'tt_label': '<b>{point.x:.1f} reads/kbp</b>: {point.y:,.2f}% duplicates', 'xPlotLines': [{'color': 'green', 'dashStyle': 'LongDash', 'label': {'style': {'color': 'green'}, 'text': '0.5 RPKM', 'verticalAlign': 'bottom', 'y': -65}, 'value': 0.5, 'width': 1}, {'color': 'red', 'dashStyle': 'LongDash', 'label': {'style': {'color': 'red'}, 'text': '1 read/bp', 'verticalAlign': 'bottom', 'y': -65}, 'value': 1000, 'width': 1}], 'id': 'dupradar-plot'}:
        validation | • Deprecated field 'xLog'. Use 'xlog' instead
        validation | • Deprecated field 'xPlotLines'. Use 'x_lines' instead
    custom_content | dupradar: Found 1 samples (linegraph)
    custom_content | DupInt: Found 13 General Statistics columns
    custom_content | biotype_counts: Found 1 samples (bargraph)
    custom_content | biotype-gs: Found 13 General Statistics columns
    custom_content | star_salmon_deseq2_clustering: Found 13 samples (heatmap)
    custom_content | star_salmon_deseq2_pca: Found 1 samples (scatter)
    custom_content | nf-core-rnaseq-summary: Found 1 sample (html)
    custom_content | software_versions: Found 1 sample (html)
            picard | Found 13 MarkDuplicates reports
            preseq | Found 13 reports
          qualimap | Found 13 RNASeq reports
             rseqc | Found 13 read_distribution reports
             rseqc | Found 13 inner_distance reports
             rseqc | Found 13 read_duplication reports
             rseqc | Found 13 junction_annotation reports
             rseqc | Found 13 junction_saturation reports
             rseqc | Found 13 infer_experiment reports
             rseqc | Found 13 bam_stat reports
          samtools | Found 13 stats reports
          samtools | Found 13 flagstat reports
          samtools | Found 13 idxstats reports
              star | Found 13 reports
            fastqc | Found 26 reports
          cutadapt | Found 26 reports
            fastqc | Found 26 reports
       multiqc_ngi | Found one NGI project id: P30455
       multiqc_ngi | Found 38 samples in StatusDB
       multiqc_ngi | Matched meta for 13 samples from StatusDB with report sample names
       multiqc_ngi | Updating existing analysis record in StatusDB
       multiqc_ngi | Out of range float values are not JSON compliant
       file_search | Only using modules: picard, preseq, qualimap, rseqc, samtools, star, fastqc, cutadapt, fastqc, dupradar-module, featurecounts_biotype, star_salmon_deseq2_clustering, star_salmon_deseq2_pca, nf-core-rnaseq-summary-module, software_versions-module

Traceback (most recent call last):
  File "/envs/NGI/bin/multiqc", line 8, in <module>
    sys.exit(run_multiqc())
             ^^^^^^^^^^^^^
  File "/envs/NGI/lib/python3.11/site-packages/multiqc/__main__.py", line 21, in run_multiqc
    multiqc.run_cli(prog_name="multiqc")
  File "/envs/NGI/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/NGI/lib/python3.11/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/envs/NGI/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/NGI/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/NGI/lib/python3.11/site-packages/multiqc/multiqc.py", line 448, in run_cli
    result = run(*analysis_dir, clean_up=clean_up, cfg=cfg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/NGI/lib/python3.11/site-packages/multiqc/multiqc.py", line 518, in run
    write_results()
  File "/envs/NGI/lib/python3.11/site-packages/multiqc/core/write_results.py", line 52, in write_results
    _write_data_files()
  File "/envs/NGI/lib/python3.11/site-packages/multiqc/core/write_results.py", line 418, in _write_data_files
    megaqc.multiqc_api_post(dump)
  File "/envs/NGI/lib/python3.11/site-packages/multiqc/utils/megaqc.py", line 20, in multiqc_api_post
    post_data = dump_json({"data": exported_data}, ensure_ascii=False, indent=2)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dump_json() missing 1 required positional argument: 'filehandle'
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [ ] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Fixed now in `main`, will be released soon!
