### ISSUE TITLE
Custom content: allow dict input to heatmap

### ISSUE THREAD

**Issue by nsharp2** [MultiQC/MultiQC#2745]
### Description of bug

Hello, I've been trying to plot a simple heatmap as a test with MultiQC v1.20 and MultiQC v1.23. I've been running MultiQC on a directory containing my JSON file (attached below), which contains my data as a dictionary of dictionaries as specified on the [MultiQC documentation](https://multiqc.info/docs/development/plots/#heatmaps). On v1.23, MultiQC will error with the message `Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]`. On v1.20, MultiQC will error unless the `min`, `xcats`, and `ycats` parameters are filled out, even though they should not be required for a dictionary of dictionaries. After providing those three parameters on the JSON file, MultiQC v1.20 finishes without error, but the report continually displays an empty loading heatmap.

### File that triggers the error

[annotation_heatmap_mqc.json](https://github.com/user-attachments/files/16534936/annotation_heatmap_mqc.json)

### MultiQC Error log

```console
v1.23 Error:

/// MultiQC 🔍 v1.23

       file_search | Search path: /home/nsharp/mambaforge/envs/heatmap/annotation_heatmap
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2
╭────────────────────────────────────────────────────── Oops! The 'custom_content' MultiQC module broke... ───────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                 │
│ Please attach a file that triggers the error. The last file found was: ./annotation_heatmap_mqc.json                                                            │
│                                                                                                                                                                 │
│ Traceback (most recent call last):                                                                                                                              │
│   File "/home/nsharp/mambaforge/envs/heatmap/lib/python3.12/site-packages/multiqc/core/exec_modules.py", line 69, in exec_modules                               │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                                     │
│                                                                        ^^^^^^^^^^^^^^^^^^^^                                                                     │
│   File "/home/nsharp/mambaforge/envs/heatmap/lib/python3.12/site-packages/multiqc/modules/custom_content/custom_content.py", line 280, in custom_module_classes │
│     parsed_modules[mod_id].add_cc_section(c_id, mod)                                                                                                            │
│   File "/home/nsharp/mambaforge/envs/heatmap/lib/python3.12/site-packages/multiqc/modules/custom_content/custom_content.py", line 422, in add_cc_section        │
│     plot = heatmap.plot(                                                                                                                                        │
│            ^^^^^^^^^^^^^                                                                                                                                        │
│   File "/home/nsharp/mambaforge/envs/heatmap/lib/python3.12/site-packages/multiqc/plots/heatmap.py", line 54, in plot                                           │
│     return heatmap.plot(data, pconf, xcats, ycats)                                                                                                              │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                              │
│   File "/home/nsharp/mambaforge/envs/heatmap/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap.py", line 57, in plot                                    │
│     return HeatmapPlot.create(rows, pconfig, xcats, ycats)                                                                                                      │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                      │
│   File "/home/nsharp/mambaforge/envs/heatmap/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap.py", line 184, in create                                 │
│     Dataset.create(                                                                                                                                             │
│   File "/home/nsharp/mambaforge/envs/heatmap/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap.py", line 84, in create                                  │
│     dataset = Dataset(                                                                                                                                          │
│               ^^^^^^^^                                                                                                                                          │
│   File "/home/nsharp/mambaforge/envs/heatmap/lib/python3.12/site-packages/pydantic/main.py", line 193, in __init__                                              │
│     self.__pydantic_validator__.validate_python(data, self_instance=self)                                                                                       │
│ pydantic_core._pydantic_core.ValidationError: 1 validation error for Dataset                                                                                    │
│ rows.0                                                                                                                                                          │
│   Input should be a valid list [type=list_type, input_value={'sample 1': {'one': 0.9,...four': 0.6, 'six': 0.3}}, input_type=dict]                              │
│     For further information visit https://errors.pydantic.dev/2.8/v/list_type                                                                                   │
│                                                                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
           multiqc | No analysis results found. Cleaning up…


v1.20 Error if `min` is not provided in the JSON file:

  /// MultiQC 🔍 | v1.20

|           multiqc | MultiQC Version v1.23 now available!
|           multiqc | Search path : /home/nsharp/mambaforge/envs/heatmap/annotation_heatmap
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
╭────────────────────────────────────────────────────── Oops! The 'custom_content' MultiQC module broke... ──────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                │
│ Please attach a file that triggers the error. The last file found was: ./annotation_heatmap_mqc.json                                                           │
│                                                                                                                                                                │
│ Traceback (most recent call last):                                                                                                                             │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/multiqc.py", line 712, in run                                                 │
│     output = mod()                                                                                                                                             │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/modules/custom_content/custom_content.py", line 257, in custom_module_classes │
│     parsed_modules[mod_id].add_cc_section(c_id, mod)                                                                                                           │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/modules/custom_content/custom_content.py", line 384, in add_cc_section        │
│     plot = heatmap.plot(mod["data"], mod["config"].get("xcats"), mod["config"].get("ycats"), pconfig)                                                          │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/plots/heatmap.py", line 57, in plot                                           │
│     return heatmap.plot(data, xcats, ycats, pconfig)                                                                                                           │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/plots/plotly/heatmap.py", line 29, in plot                                    │
│     p = HeatmapPlot(pconfig, rows, xcats, ycats)                                                                                                               │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/plots/plotly/heatmap.py", line 106, in __init__                               │
│     assert isinstance(val, (int, float))                                                                                                                       │
│ AssertionError                                                                                                                                                 │
│                                                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete


v1.20 Error if `min` is provided but `ycats` is not provided in JSON:

  /// MultiQC 🔍 | v1.20

|           multiqc | MultiQC Version v1.23 now available!
|           multiqc | Search path : /home/nsharp/mambaforge/envs/heatmap/annotation_heatmap
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
╭────────────────────────────────────────────────────── Oops! The 'custom_content' MultiQC module broke... ──────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                │
│ Please attach a file that triggers the error. The last file found was: ./annotation_heatmap_mqc.json                                                           │
│                                                                                                                                                                │
│ Traceback (most recent call last):                                                                                                                             │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/multiqc.py", line 712, in run                                                 │
│     output = mod()                                                                                                                                             │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/modules/custom_content/custom_content.py", line 257, in custom_module_classes │
│     parsed_modules[mod_id].add_cc_section(c_id, mod)                                                                                                           │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/modules/custom_content/custom_content.py", line 384, in add_cc_section        │
│     plot = heatmap.plot(mod["data"], mod["config"].get("xcats"), mod["config"].get("ycats"), pconfig)                                                          │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/plots/heatmap.py", line 57, in plot                                           │
│     return heatmap.plot(data, xcats, ycats, pconfig)                                                                                                           │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/plots/plotly/heatmap.py", line 29, in plot                                    │
│     p = HeatmapPlot(pconfig, rows, xcats, ycats)                                                                                                               │
│   File "/home/nsharp/mambaforge/envs/multiqc/lib/python3.9/site-packages/multiqc/plots/plotly/heatmap.py", line 119, in __init__                               │
│     num_rows = len(ycats)                                                                                                                                      │
│ TypeError: object of type 'NoneType' has no len()                                                                                                              │
│                                                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
The error says that the data format is expected to be a list. So the JSON that would work would look like this:

```
{
    "id": "annotation_alignment_stats",
    "plot_type": "heatmap",
    "pconfig": {
        "title": "Annotation stats (DRAMv)",
	    "min": 0
    },
    "xcats": ["one", "two", "three", "four", "five", "six"],
    "ycats": ["sample 1", "sample 2"],
    "data": [
        [
            0.9,
            0.87,
            0.73,
            0.6,
            0.2,
            0
        ],
        [
            0,
            1,
            0.7,
            0.6,
            0,
            0.3
        ]
    ]
}
```

**Comment by vladsavelyev** [comment]
Having said that, we can support a dictionary format as well, as it's more convenient. I'll make an update.

**Comment by vladsavelyev** [comment]
Okay, done that with https://github.com/MultiQC/MultiQC/pull/2761

Note though you would still need to swap xcats and ycats, i.e. it should go this way:

```
{
    "id": "annotation_alignment_stats",
    "plot_type": "heatmap",
    "pconfig": {
        "title": "Annotation stats (DRAMv)",
	    "min": 0
    },
    "ycats": ["sample 1", "sample 2"],
    "xcats": ["one", "two", "three", "four", "five", "six"],
    "data": {
        "sample 1": {
            "one": 0.9,
            "two": 0.87,
            "three": 0.73,
            "four": 0.6,
            "five": 0.2
        },
        "sample 2": {
            "two": 1,
            "three": 0.7,
            "four": 0.6,
            "six": 0.3
        }
    }
}

```

**Comment by nsharp2** [comment]
Thank you so much for the quick adjustment and response! I really appreciate it.
