### ISSUE TITLE
MultiQC fails to produce Nonpareil reports when the number of files provided is thirteen or more

### ISSUE THREAD

**Issue by jlanga** [MultiQC/MultiQC#2747]
### Description of bug

When processing multiple json files exported from nonpareil, if that number is 12 or lower it works perfectly fine. The moment it tries to process 13 or more it fails.

### File that triggers the error

[M301474.lib1.json](https://github.com/user-attachments/files/16549388/M301474.lib1.json)
[M301475.lib1.json](https://github.com/user-attachments/files/16549391/M301475.lib1.json)
[M301476.lib1.json](https://github.com/user-attachments/files/16549393/M301476.lib1.json)
[M301477.lib1.json](https://github.com/user-attachments/files/16549394/M301477.lib1.json)
[M301478.lib1.json](https://github.com/user-attachments/files/16549395/M301478.lib1.json)
[M301480.lib1.json](https://github.com/user-attachments/files/16549397/M301480.lib1.json)
[M301481.lib1.json](https://github.com/user-attachments/files/16549398/M301481.lib1.json)
[M301482.lib1.json](https://github.com/user-attachments/files/16549399/M301482.lib1.json)
[M301483.lib1.json](https://github.com/user-attachments/files/16549400/M301483.lib1.json)
[M301484.lib1.json](https://github.com/user-attachments/files/16549401/M301484.lib1.json)
[M301485.lib1.json](https://github.com/user-attachments/files/16549402/M301485.lib1.json)
[M301486.lib1.json](https://github.com/user-attachments/files/16549403/M301486.lib1.json)
[M301487.lib1.json](https://github.com/user-attachments/files/16549404/M301487.lib1.json)
[M301488.lib1.json](https://github.com/user-attachments/files/16549405/M301488.lib1.json)

### MultiQC Error log

```console
# Thirteen files (fail)
$ multiqc $(find nonpareil_test -name "*.json" | sort)                                                                                                                                                            ✔  multiqc Py  16:21:16 

/// MultiQC 🔍 v1.23

       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301474.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301475.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301476.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301477.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301478.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301480.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301481.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301482.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301483.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301484.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301485.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301486.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301487.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301488.lib1.json
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 14/14  
         nonpareil | Found 14 reports
╭────────────────────────────────────────────────────── Oops! The 'nonpareil' MultiQC module broke... ───────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                            │
│ Please attach a file that triggers the error. The last file found was: nonpareil_test/M301488.lib1.json                                                    │
│                                                                                                                                                            │
│ Traceback (most recent call last):                                                                                                                         │
│   File "/home/jlanga/.miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/core/exec_modules.py", line 69, in exec_modules                         │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                                │
│                                                                        ^^^^^^^^^^^^^^^^^^^^                                                                │
│   File "/home/jlanga/.miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/modules/nonpareil/nonpareil.py", line 65, in __init__                   │
│     self.nonpareil_redundancy_plot()                                                                                                                       │
│   File "/home/jlanga/.miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/modules/nonpareil/nonpareil.py", line 327, in nonpareil_redundancy_plot │
│     s_name: data.get("nonpareil_col", data_colors_default.pop(0))                                                                                          │
│                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                           │
│ IndexError: pop from empty list                                                                                                                            │
│                                                                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
           multiqc | No analysis results found. Cleaning up…


# The first twelve files (success)
$ multiqc $(find nonpareil_test -name "*.json" | sort | head -12)                                                                                                                                               1 ✘  multiqc Py  16:21:27 

/// MultiQC 🔍 v1.23

       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301474.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301475.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301476.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301477.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301478.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301480.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301481.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301482.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301483.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301484.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301485.lib1.json
       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301486.lib1.json
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 12/12  
         nonpareil | Found 12 reports
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete

# The last file (success)
$ multiqc $(find nonpareil_test -name "*.json" | sort |tail  -1)                                                                                                                                                  ✔  multiqc Py  16:21:55 

/// MultiQC 🔍 v1.23

       file_search | Search path: /home/jlanga/workspace/3d/mg_quant/nonpareil_test/M301488.lib1.json
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1  
         nonpareil | Found 1 reports
     write_results | Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
     write_results | Data        : multiqc_data_1
     write_results | Report      : multiqc_report_1.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Argh, what a elusive bug 🤦  Sorry about it! Fixed with https://github.com/MultiQC/MultiQC/pull/2752
