### ISSUE TITLE
Issue with Sample Names and Custom Content

### ISSUE THREAD

**Issue by whottel** [MultiQC/MultiQC#2766]
### Description of bug

Using sample names such as "1", "2", "3" breaks the custom content module. The same setup as detailed below with names such as "SRR12345", "ERR6789" works without issue. 

### File that triggers the error

[Multiqc_files.zip](https://github.com/user-attachments/files/16615091/Multiqc_files.zip)

### MultiQC Error log

```console
Run command part of larger job script:
singularity exec -e -B .:/data --pwd /data -H ${vhome} ${multiqc_image} multiqc ${type_out_dir} -d -dd 1 --config ${multiqc_config} --exclude flash --outdir ${type_out_dir}
/// MultiQC 🔍 v1.23

            config | Loading config settings from: /Shared/SHL-BUG/multiqc/multi_config_type.yaml
     update_config | Prepending directory to sample names
       file_search | Search path: /Shared/SHL-BUG/workspaces/whottel/scratch/Type_Donut_Falls_test/ONT_only/type_data
       file_search | Excluding modules 'flash'

╭───────────── Oops! The 'custom_content' MultiQC module broke... ─────────────╮
│ Please copy this log and report it at                                        │
│ https://github.com/MultiQC/MultiQC/issues                                    │
│ Please attach a file that triggers the error. The last file found was:       │
│ /Shared/SHL-BUG/workspaces/whottel/scratch/Type_Donut_Falls_test/ONT_only/ty │
│ pe_data/mash_results.txt                                                     │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/core/exec_modules.py │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = modul │
│                                                                        ^^^^^ │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/custom_conte │
│     parsed_data, parsed_conf = _parse_txt(f, m_config, non_header_lines)     │
│                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/custom_conte │
│     assert isinstance(s[0], str)                                             │
│            ^^^^^^^^^^^^^^^^^^^^^                                             │
│ AssertionError                                                               │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
             quast | Found 3 reports
            kraken | Found 3 reports
            fastqc | Found 3 reports
       file_search | Excluding modules 'flash'

     write_results | Data        : ../Shared/SHL-BUG/workspaces/whottel/scratch/Type_Donut_Falls_test/ONT_only/type_data/multiqc_data
     write_results | Report      : ../Shared/SHL-BUG/workspaces/whottel/scratch/Type_Donut_Falls_test/ONT_only/type_data/multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by whottel** [comment]
Thanks for looking into this. We run multqc using the container image posted here: https://hub.docker.com/r/multiqc/multiqc/, so I will check if this fix is working when the next release is posted. 
And yes, for this particular example there should be no values as none of the samples had a mash result above a predefined cutoff value.

**Comment by whottel** [comment]
Hello,
I tried v1.24 but unfortunately I am still seeing input_type error. Also, I am seeing several python syntax warnings with 1.24:
```
Apptainer> multiqc type_data/ -d -dd 1 --config /Shared/SHL-BUG/multiqc/multi_config_type.yaml --exclude flash --force

/usr/local/lib/python3.12/site-packages/pyaml_env/parse_config.py:58: SyntaxWarning: invalid escape sequence '\w'
  type_tag_pattern = re.compile(f'({type_tag}\w+\s)')
/usr/local/lib/python3.12/site-packages/colormath/color_objects.py:452: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- Original illuminant: %s", self.illuminant)
/usr/local/lib/python3.12/site-packages/colormath/color_objects.py:453: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- Target illuminant: %s", target_illuminant)
/usr/local/lib/python3.12/site-packages/colormath/color_objects.py:459: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \* Applying transformation from %s to %s ",
/usr/local/lib/python3.12/site-packages/colormath/chromatic_adaptation.py:85: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \* Applying adaptation matrix: %s", adaptation)
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:40: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \* Applying RGB conversion matrix: %s->%s",
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:488: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- Target RGB space: %s", target_rgb)
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:490: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- Target native illuminant: %s", target_illum)
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:491: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- XYZ color's illuminant: %s", cobj.illuminant)
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:497: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \* Applying transformation from %s to %s ",
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:503: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \*   New values: %.3f, %.3f, %.3f",

/// d=862577;https://multiqc.infoMultiQC 🔍 v1.24

            config | Loading config settings from: /Shared/SHL-BUG/multiqc/multi_config_type.yaml
     update_config | Prepending directory to sample names
       file_search | Search path: /Shared/SHL-BUG/workspaces/whottel/scratch/Type_Donut_Falls_test/ONT_only/test_new2/type_data
       file_search | Excluding modules 'flash'
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 124/124  
╭───────────────────────────────────────── Oops! The 'custom_content' MultiQC module broke... ──────────────────────────────────────────╮
│ Please copy this log and report it at d=942437;https://github.com/MultiQC/MultiQC/issues/new?template=bug_report.md&title=custom_content%20module%20-%20typehttps://github.com/MultiQC/MultiQC/issues                                                       │
│ Please attach a file that triggers the error. The last file found was: type_data/amrfinder/amrfinder_for_multiqc_overall.csv          │
│                                                                                                                                       │
│ Traceback (most recent call last):                                                                                                    │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/core/exec_modules.py", line 68, in exec_modules                               │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                           │
│                                                                        ^^^^^^^^^^^^^^^^^^^^                                           │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/custom_content/custom_content.py", line 282, in custom_module_classes │
│     parsed_modules[mod_id].add_cc_section(c_id, mod_dict)                                                                             │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/custom_content/custom_content.py", line 388, in add_cc_section        │
│     plot = heatmap.plot(                                                                                                              │
│            ^^^^^^^^^^^^^                                                                                                              │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/heatmap.py", line 54, in plot                                           │
│     return heatmap.plot(data, pconf, xcats, ycats)                                                                                    │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                    │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap.py", line 57, in plot                                    │
│     return HeatmapPlot.create(rows, pconfig, xcats, ycats)                                                                            │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                            │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap.py", line 185, in create                                 │
│     Dataset.create(                                                                                                                   │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap.py", line 84, in create                                  │
│     dataset = Dataset(                                                                                                                │
│               ^^^^^^^^                                                                                                                │
│   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 193, in __init__                                              │
│     self.__pydantic_validator__.validate_python(data, self_instance=self)                                                             │
│ pydantic_core._pydantic_core.ValidationError: 3 validation errors for Dataset                                                         │
│ ycats.0                                                                                                                               │
│   Input should be a valid string [type=string_type, input_value=123.0, input_type=float]                                              │
│     For further information visit https://errors.pydantic.dev/2.8/v/string_type                                                       │
│ ycats.1                                                                                                                               │
│   Input should be a valid string [type=string_type, input_value=465.0, input_type=float]                                              │
│     For further information visit https://errors.pydantic.dev/2.8/v/string_type                                                       │
│ ycats.2                                                                                                                               │
│   Input should be a valid string [type=string_type, input_value=789.0, input_type=float]                                              │
│     For further information visit https://errors.pydantic.dev/2.8/v/string_type                                                       │
│                                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
             quast | Found 3 reports
            kraken | Found 3 reports
            fastqc | Found 3 reports
       file_search | Excluding modules 'flash'
     write_results | Data        : multiqc_data   (overwritten)
     write_results | Report      : multiqc_report.html   (overwritten)
           multiqc | MultiQC complete
```
Also please find attached the relevant files that the custom config is meant to be parsing. 
[temp.zip](https://github.com/user-attachments/files/16680465/temp.zip)

**Comment by whottel** [comment]
Hello, I tried out V1.25 and my custom content issue is resolved.
I do notice however, I continue to see Python syntax warnings in my log file


```
Running MultiQC on /Shared/SHL-BUG/workspaces/whottel/scratch/Type_Donut_Falls_test/Hybrid/test_new_241001/type_data 
/usr/local/lib/python3.12/site-packages/colormath/color_objects.py:452: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- Original illuminant: %s", self.illuminant)
/usr/local/lib/python3.12/site-packages/colormath/color_objects.py:453: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- Target illuminant: %s", target_illuminant)
/usr/local/lib/python3.12/site-packages/colormath/color_objects.py:459: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \* Applying transformation from %s to %s ",
/usr/local/lib/python3.12/site-packages/colormath/chromatic_adaptation.py:85: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \* Applying adaptation matrix: %s", adaptation)
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:40: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \* Applying RGB conversion matrix: %s->%s",
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:488: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- Target RGB space: %s", target_rgb)
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:490: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- Target native illuminant: %s", target_illum)
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:491: SyntaxWarning: invalid escape sequence '\-'
  logger.debug("  \- XYZ color's illuminant: %s", cobj.illuminant)
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:497: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \* Applying transformation from %s to %s ",
/usr/local/lib/python3.12/site-packages/colormath/color_conversions.py:503: SyntaxWarning: invalid escape sequence '\*'
  logger.debug("  \*   New values: %.3f, %.3f, %.3f",

/// MultiQC 🔍 v1.25
```
