### ISSUE TITLE
KeyError: 'analysis_tab'

### ISSUE THREAD

**Issue by nick-youngblut** [MultiQC/MultiQC#2767]
### Description of bug

`multiqc .` on cellranger output (74 samples)

The error:

```
│ Traceback (most recent call last):                                                                                                                     │
│   File "/home/nickyoungblut/miniforge3/envs/sandbox/lib/python3.10/site-packages/multiqc/core/exec_modules.py", line 69, in exec_modules               │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                            │
│   File "/home/nickyoungblut/miniforge3/envs/sandbox/lib/python3.10/site-packages/multiqc/modules/cellranger/cellranger.py", line 37, in __init__       │
│     n["count"] = self.parse_count_html()                                                                                                               │
│   File "/home/nickyoungblut/miniforge3/envs/sandbox/lib/python3.10/site-packages/multiqc/modules/cellranger/count.py", line 32, in parse_count_html    │
│     self.parse_count_report(f)                                                                                                                         │
│   File "/home/nickyoungblut/miniforge3/envs/sandbox/lib/python3.10/site-packages/multiqc/modules/cellranger/count.py", line 344, in parse_count_report │
│     "title": f"Cell Ranger count: {summary['analysis_tab']['median_gene_plot']['help']['title']}",                                                     │
│ KeyError: 'analysis_tab'
```

The issue is that there were no cells for one sample (attached), and multiqc cannot handle this edge case.

<img width="1093" alt="Screenshot 2024-08-14 at 2 48 25 PM" src="https://github.com/user-attachments/assets/97de0ea8-be9f-4880-8186-ac9bffcdf6f6">

### File that triggers the error

[web_summary.html.zip](https://github.com/user-attachments/files/16619313/web_summary.html.zip)

### MultiQC Error log

```console
/// MultiQC 🔍 v1.23

       file_search | Search path: /home/nickyoungblut/20240807_SspArc0178_SspArc0180/scrnaseq
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3333/3333
╭──────────────────────────────────────────────────── Oops! The 'cellranger' MultiQC module broke... ────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                        │
│ Please attach a file that triggers the error. The last file found was: cellranger/count/LB_4008_10_LTG/outs/web_summary.html                           │
│                                                                                                                                                        │
│ Traceback (most recent call last):                                                                                                                     │
│   File "/home/nickyoungblut/miniforge3/envs/sandbox/lib/python3.10/site-packages/multiqc/core/exec_modules.py", line 69, in exec_modules               │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                            │
│   File "/home/nickyoungblut/miniforge3/envs/sandbox/lib/python3.10/site-packages/multiqc/modules/cellranger/cellranger.py", line 37, in __init__       │
│     n["count"] = self.parse_count_html()                                                                                                               │
│   File "/home/nickyoungblut/miniforge3/envs/sandbox/lib/python3.10/site-packages/multiqc/modules/cellranger/count.py", line 32, in parse_count_html    │
│     self.parse_count_report(f)                                                                                                                         │
│   File "/home/nickyoungblut/miniforge3/envs/sandbox/lib/python3.10/site-packages/multiqc/modules/cellranger/count.py", line 344, in parse_count_report │
│     "title": f"Cell Ranger count: {summary['analysis_tab']['median_gene_plot']['help']['title']}",                                                     │
│ KeyError: 'analysis_tab'                                                                                                                               │
│                                                                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
            fastqc | Found 148 reports
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Fixed now with https://github.com/MultiQC/MultiQC/pull/2771
