### ISSUE TITLE
MQC Custom Content BUg 

### ISSUE THREAD

**Issue by apeltzer** [MultiQC/MultiQC#2785]
### Description of bug

```
│ Please copy this log and report it at                                        │
  │ https://github.com/MultiQC/MultiQC/issues                                    │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ 17/Posctrl_linearity_mqc.png                                                 │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/core/exec_modules.py │
  │     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = modul │
  │                                                                        ^^^^^ │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/custom_conte │
  │     parsed_modules[mod_id].add_cc_section(c_id, mod_dict)                    │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/custom_conte │
  │     plot = heatmap.plot(                                                     │
  │            ^^^^^^^^^^^^^                                                     │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/heatmap.py", l │
  │     return heatmap.plot(data, pconf, xcats, ycats)                           │
  │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                           │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap │
  │     return HeatmapPlot.create(rows, pconfig, xcats, ycats)                   │
  │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap │
  │     Dataset.create(                                                          │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap │
  │     dataset = Dataset(                                                       │
  │               ^^^^^^^^                                                       │
  │   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 193, │
  │     self.__pydantic_validator__.validate_python(data, self_instance=self)    │
  │ pydantic_core._pydantic_core.ValidationError: 1 validation error for Dataset │
  │ ycats.0                                                                      │
  │   Input should be a valid string [type=string_type, input_value=1.0, input_t │
  │     For further information visit https://errors.pydantic.dev/2.8/v/string_t │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
             multiqc | No analysis results found. Cleaning up…

Work dir:
  /workspace/nanostring/work/95/dadef2d32645f0bdb7bc1fd987d7ed

### File that triggers the error

You can find an example that fails here: https://github.com/nf-core/nanostring/actions/runs/10467756513/job/28987183655?pr=76 

I am not super sure why it worked with 1.19 @vladsavelyev 

### MultiQC Error log

```console
│ Please copy this log and report it at                                        │
  │ https://github.com/MultiQC/MultiQC/issues                                    │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ 17/Posctrl_linearity_mqc.png                                                 │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/core/exec_modules.py │
  │     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = modul │
  │                                                                        ^^^^^ │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/custom_conte │
  │     parsed_modules[mod_id].add_cc_section(c_id, mod_dict)                    │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/custom_conte │
  │     plot = heatmap.plot(                                                     │
  │            ^^^^^^^^^^^^^                                                     │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/heatmap.py", l │
  │     return heatmap.plot(data, pconf, xcats, ycats)                           │
  │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                           │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap │
  │     return HeatmapPlot.create(rows, pconfig, xcats, ycats)                   │
  │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap │
  │     Dataset.create(                                                          │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/heatmap │
  │     dataset = Dataset(                                                       │
  │               ^^^^^^^^                                                       │
  │   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 193, │
  │     self.__pydantic_validator__.validate_python(data, self_instance=self)    │
  │ pydantic_core._pydantic_core.ValidationError: 1 validation error for Dataset │
  │ ycats.0                                                                      │
  │   Input should be a valid string [type=string_type, input_value=1.0, input_t │
  │     For further information visit https://errors.pydantic.dev/2.8/v/string_t │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
             multiqc | No analysis results found. Cleaning up…

Work dir:
  /workspace/nanostring/work/95/dadef2d32645f0bdb7bc1fd987d7ed
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

You may find the CI logfiles here but can also reproduce this very easily with MultiQC 1.24:

https://github.com/nf-core/nanostring/actions/runs/10467756513/job/28987183655?pr=76

`nextflow run nf-core/nanostring -r bump-pr -profile docker,test_scores,docker`

**Comment by vladsavelyev** [comment]
Fixed with https://github.com/MultiQC/MultiQC/pull/2787

**Comment by vladsavelyev** [comment]
Just want to comment on this PR. Please make sure that the issue comment formatting is not broken, and there are no obvious typos. And please try to attach a reproducible example, if possible. That way, we would be happy to prioritize and resolve an issue quicker.
