### ISSUE TITLE
Pydantic errors with new AnchorT class

### ISSUE THREAD

**Issue by Sxmple-DavidSchmidt** [MultiQC/MultiQC#2809]
### Description of bug

I updated my fork to include the new changes, pushed ~4 days ago. This change includes adding the new types`AnchorT`, `ModuleIdT` and `SectionIdT`. With these changes, the code breaks, meaning you cannot even run `python3 -m multiqc --help`. This is pretty bothersome because I am working on a new module, and now I can't do so any more.

For anyone having the same problems:
As a temporary fix, you can change the line `anchor: Optional[AnchorT] = None` to `anchor: Optional[str] = None` in `multiqc/plots/plotly/plot.py` and the line `anchor: AnchorT` to `anchor: str` in `multiqc/plots/table_object.py`. This at least makes MultiQC run so you can continue developing. 

### MultiQC Error log

```console
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/dschmidt/PycharmProjects/MultiQC/multiqc/__init__.py", line 23, in <module>
    from multiqc import report  # noqa: E402
  File "/home/dschmidt/PycharmProjects/MultiQC/multiqc/report.py", line 30, in <module>
    from multiqc.base_module import BaseMultiqcModule
  File "/home/dschmidt/PycharmProjects/MultiQC/multiqc/base_module.py", line 22, in <module>
    from multiqc.plots.plotly.plot import Plot
  File "/home/dschmidt/PycharmProjects/MultiQC/multiqc/plots/plotly/plot.py", line 28, in <module>
    class PConfig(ValidatedConfig):
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 205, in __new__
    complete_model_class(
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 534, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/main.py", line 643, in __get_pydantic_core_schema__
    return handler(source)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 512, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 784, in _generate_schema_inner
    return self._model_schema(obj)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 591, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 591, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 947, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1134, in _common_field_schema
    schema = self._apply_annotations(
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1890, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1871, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 789, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 871, in match_type
    return self._match_generic_type(obj, origin)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 895, in _match_generic_type
    return self._union_schema(obj)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1207, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 512, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 789, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 875, in match_type
    return self._unknown_type_schema(obj)
  File "/home/dschmidt/PycharmProjects/MultiQC/.mqcv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 415, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for multiqc.types.AnchorT. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type
```
```


### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this 🫤  Should be fixed now in `main`. I also merged `main` into your PR to make sure the tests pass 👍

**Comment by LindeNozomiLeo** [comment]
Hi,

I just tried to run multiqc and am still running into this error

**Comment by Sxmple-DavidSchmidt** [comment]
Me too. The error is the same too. I tried recreating it and It's pretty simple:

```python3
from typing_extensions import NewType
from pydantic import BaseModel

AnchorT = NewType("AnchorT", str)

class FailingClass(BaseModel):
    anchor: AnchorT = None
```

I don't really know how PyDantic works nor what it does, but it seems to struggle with custom types. The same code works with `anchor: str`, `anchor: int`, `anchor: tuple` or just about any basic type. It fails with the instances of `NewType` or classes written like this:

```python3
class Anchor:
    value: str

    def __init__(self, value: str):
        self.value = value
```

**Comment by vladsavelyev** [comment]
Ah, that's the legacy `from typing_extensions import NewType` vs `from typing import NewType`.

What's the Python version you are using in that environment?

**Comment by Sxmple-DavidSchmidt** [comment]
I am running `Python 3.10.12` (inside and outside the environment).
If I use `typing.NewType` instead like this: 
```python3
from typing import NewType
from pydantic import BaseModel

AnchorT = NewType("AnchorT", str)

class FailingClass(BaseModel):
    anchor: AnchorT = None
```
everything works as intended

**Comment by vladsavelyev** [comment]
Thanks! So this should do it: https://github.com/MultiQC/MultiQC/pull/2820
