### ISSUE TITLE
nf-core pipeline crashes when using quay.io/biocontainers/multiqc > v1.21

### ISSUE THREAD

**Issue by kedhammar** [MultiQC/MultiQC#2812]
### Description of bug

I am working on an [nf-core pipeline](https://github.com/nf-core/seqinspector/pull/20) and had to bump the MultiQC module from 1.21 from 1.24 to prevent it from crashing on GitPod.

Now it's working on GitPod but crashes when run locally on my M1 Mac.

```
Command error:
  #16 0x555558d15f18 content::BrowserProcessSubThread::IOThreadRun()
  #17 0x55555a36c874 base::Thread::ThreadMain()
  #18 0x55555a38ecaa base::(anonymous namespace)::ThreadFunc()
  #19 0x2aaaab656134 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x89133)
  #20 0x2aaaab6d5a40 __clone
  Task trace:
  #0 0x555558d5905e content::internal::ChildProcessLauncherHelper::PostLaunchOnLauncherThread()
  #1 0x555558d58afc content::internal::ChildProcessLauncherHelper::StartLaunchOnClientThread()
  #2 0x55555928a7c2 content::VizProcessTransportFactory::ConnectHostFrameSinkManager()
  #3 0x55555a9ae26f mojo::SimpleWatcher::Context::Notify()
  #4 0x55555928a7c2 content::VizProcessTransportFactory::ConnectHostFrameSinkManager()
  Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.
  
  Received signal 6
  #0 0x55555a37ed79 base::debug::CollectStackTrace()
  #1 0x55555a2fc633 base::debug::StackTrace::StackTrace()
  #2 0x55555a37e95b base::debug::(anonymous namespace)::StackDumpSignalHandler()
  #3 0x2aaaab609050 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x3c04f)
  #4 0x2aaaab657e2c (/usr/lib/x86_64-linux-gnu/libc.so.6+0x8ae2b)
  #5 0x2aaaab608fb2 gsignal
  #6 0x2aaaab5f3472 abort
  #7 0x55555a37d8f5 base::debug::BreakDebugger()
  #8 0x55555a30c5b2 logging::LogMessage::~LogMessage()
  #9 0x555558e68907 content::(anonymous namespace)::IntentionallyCrashBrowserForUnusableGpuProcess()
  #10 0x555558e666be content::GpuDataManagerImplPrivate::FallBackToNextGpuMode()
  #11 0x555558e64c53 content::GpuDataManagerImpl::FallBackToNextGpuMode()
  #12 0x555558e6ef5f content::GpuProcessHost::RecordProcessCrash()
  #13 0x555558cf96d3 content::BrowserChildProcessHostImpl::OnProcessLaunchFailed()
  #14 0x555558d591f0 content::internal::ChildProcessLauncherHelper::PostLaunchOnClientThread()
  #15 0x555558d59435 base::internal::Invoker<>::RunOnce()
  #16 0x55555a342306 base::TaskAnnotator::RunTask()
  #17 0x55555a353cf6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
  #18 0x55555a3539ea base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
  #19 0x55555a3a0899 base::MessagePumpLibevent::Run()
  #20 0x55555a35459b base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
  #21 0x55555a32d9bd base::RunLoop::Run()
  #22 0x555558d15f18 content::BrowserProcessSubThread::IOThreadRun()
  #23 0x55555a36c874 base::Thread::ThreadMain()
  #24 0x55555a38ecaa base::(anonymous namespace)::ThreadFunc()
  #25 0x2aaaab656134 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x89133)
  #26 0x2aaaab6d5a40 __clone
    r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000008 r11: 00000000ae316e43
   r12: 0000000000000006 r13: 00002aaaae318580 r14: 00002aaaae318590 r15: 00002aaaae318598
    di: 0000000000000610  si: 000000000000061d  bp: 00002aaaae3196c0  bx: 000000000000061d
    dx: 0000000000000006  ax: 0000000000000000  cx: 0000000000000000  sp: 00002aaaae3173c0
    ip: 00002aaaab657e2c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
   trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
  [end of stack trace]
  Calling _exit(1). Core file will not be generated.
```

This seems related to https://github.com/MultiQC/MultiQC/issues/2667

### File that triggers the error

I was able to replicate the error exactly on my colleagues Macbook by the following steps:
- Use a Mac w. an M1-chip
- Check out [this commit](https://github.com/Aratz/seqinspector/tree/2e269ecc236a66866f8413a1129656ed9c1d816f)
- Run `nextflow run . -profile test,docker --outdir outdir`

The error is induced by upgrading MultiQC and can be avoided by using Conda instead of Docker. The error persists when including the `arm` profile in the command.

### MultiQC Error log

```console
/// MultiQC 🔍 v1.24.1

            config | Loading config settings from: multiqc_config.yml
            config | Loading config settings from: multiqc_config.yml
       file_search | Search path: /Users/alfred.kedhammar/code/repos/seqinspector/work/6e/931140d39f6960adbd9fc138f5a09b

    custom_content | nf-core-seqinspector-methods-description: Found 1 sample (html)
    custom_content | nf-core-seqinspector-summary: Found 1 sample (html)
            fastqc | Found 1 reports

Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 10, in <module>
    sys.exit(run_multiqc())
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/multiqc/__main__.py", line 21, in run_multiqc
    multiqc.run_cli(prog_name="multiqc")
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/multiqc/multiqc.py", line 450, in run_cli
    result = run(*analysis_dir, clean_up=clean_up, cfg=cfg, interactive=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/multiqc/multiqc.py", line 511, in run
    write_results()
  File "/usr/local/lib/python3.12/site-packages/multiqc/core/write_results.py", line 68, in write_results
    render_and_export_plots(plots_dir_name=output_names.plots_dir_name)
  File "/usr/local/lib/python3.12/site-packages/multiqc/core/write_results.py", line 276, in render_and_export_plots
    iterate_using_progress_bar(
  File "/usr/local/lib/python3.12/site-packages/multiqc/core/log_and_rich.py", line 392, in iterate_using_progress_bar
    update_fn(i, item)
  File "/usr/local/lib/python3.12/site-packages/multiqc/core/write_results.py", line 255, in update_fn
    s.plot = _plot.add_to_report(plots_dir_name=plots_dir_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/plot.py", line 527, in add_to_report
    self.flat_plot(embed_in_html=False, plots_dir_name=plots_dir_name)
  File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/plot.py", line 583, in flat_plot
    html += fig_to_static_html(
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/multiqc/plots/plotly/plot.py", line 722, in fig_to_static_html
    fig.write_image(img_buffer, **write_kwargs)
  File "/usr/local/lib/python3.12/site-packages/plotly/basedatatypes.py", line 3835, in write_image
    return pio.write_image(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plotly/io/_kaleido.py", line 266, in write_image
    img_data = to_image(
               ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plotly/io/_kaleido.py", line 143, in to_image
    img_bytes = scope.transform(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/kaleido/scopes/plotly.py", line 153, in transform
    response = self._perform_transform(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/kaleido/scopes/base.py", line 293, in _perform_transform
    self._ensure_kaleido()
  File "/usr/local/lib/python3.12/site-packages/kaleido/scopes/base.py", line 198, in _ensure_kaleido
    raise ValueError(message)
ValueError: Failed to start Kaleido subprocess. Error stream:

[0904/134821.137450:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale 
[0904/134821.417831:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale 
[0904/134821.434641:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale 
[0904/134821.426123:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
#0 0x55555a37ed79 base::debug::CollectStackTrace()
#1 0x55555a2fc633 base::debug::StackTrace::StackTrace()
#2 0x55555a30c15f logging::LogMessage::~LogMessage()
#3 0x55555a30ccde logging::LogMessage::~LogMessage()
#4 0x55555a077345 content::ZygoteMain()
#5 0x55555a0648ea content::RunZygote()
#6 0x55555a065b64 content::ContentMainRunnerImpl::Run()
#7 0x55555a063374 content::RunContentProcess()
#8 0x55555a063cfc content::ContentMain()
#9 0x55555a0b5182 headless::(anonymous namespace)::RunContentMain()
#10 0x55555a0b4fbb headless::RunChildProcessIfNeeded()
#11 0x5555580d3f09 main
#12 0x2aaaab5f424a (/usr/lib/x86_64-linux-gnu/libc.so.6+0x27249)
#13 0x2aaaab5f4305 __libc_start_main
#14 0x5555580cd3ea _start

Received signal 6
#0 0x55555a37ed79 base::debug::CollectStackTrace()
#1 0x55555a2fc633 base::debug::StackTrace::StackTrace()
#2 0x55555a37e95b [0904/134821.440008:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
#0 0x55555a37ed79 base::debug::CollectStackTrace()
#1 0x55555a2fc633 base::debug::StackTrace::StackTrace()
#2 0x55555a30c15f logging::LogMessage::~LogMessage()
#3 0x55555a30ccde logging::LogMessage::~LogMessage()
#4 0x55555a077345 content::ZygoteMain()
#5 0x55555a0648ea content::RunZygote()
#6 0x55555a065b64 content::ContentMainRunnerImpl::Run()
#7 0x55555a063374 content::RunContentProcess()
#8 0x55555a063cfc content::ContentMain()
#9 0x55555a0b5182 headless::(anonymous namespace)::RunContentMain()
#10 0x55555a0b4fbb headless::RunChildProcessIfNeeded()
#11 0x5555580d3f09 main
#12 0x2aaaab5f424a (/usr/lib/x86_64-linux-gnu/libc.so.6+0x27249)
#13 0x2aaaab5f4305 __libc_start_main
#14 0x5555580cd3ea _start

Received signal 6
#0 0x55555a37ed79 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x2aaaab609050 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x3c04f)
#4 0x2aaaab657e2c (/usr/lib/x86_64-linux-gnu/libc.so.6+0x8ae2b)
#5 0x2aaaab608fb2 gsignal
#6 0x2aaaab5f3472 abort
#7 0x55555a37d8f5 base::debug::CollectStackTrace()
#1 0x55555a2fc633 base::debug::BreakDebugger()
#8 0x55555a30c5b2 base::debug::StackTrace::StackTrace()
#2 0x55555a37e95b logging::LogMessage::~LogMessage()
#9 0x55555a30ccde base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x2aaaab609050 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x3c04f)
#4 0x2aaaab657e2c (/usr/lib/x86_64-linux-gnu/libc.so.6+0x8ae2b)
#5 0x2aaaab608fb2 gsignal
#6 0x2aaaab5f3472 abort
#7 0x55555a37d8f5 logging::LogMessage::~LogMessage()
#10 0x55555a077345 content::ZygoteMain()
#11 0x55555a0648ea base::debug::BreakDebugger()
#8 0x55555a30c5b2 content::RunZygote()
#12 0x55555a065b64 logging::LogMessage::~LogMessage()
#9 0x55555a30ccde content::ContentMainRunnerImpl::Run()
#13 0x55555a063374 logging::LogMessage::~LogMessage()
#10 0x55555a077345 content::RunContentProcess()
#14 0x55555a063cfc content::ZygoteMain()
#11 0x55555a0648ea content::ContentMain()
#15 0x55555a0b5182 content::RunZygote()
#12 0x55555a065b64 headless::(anonymous namespace)::RunContentMain()
#16 0x55555a0b4fbb content::ContentMainRunnerImpl::Run()
#13 0x55555a063374 headless::RunChildProcessIfNeeded()
#17 0x5555580d3f09 main
#18 0x2aaaab5f424a (/usr/lib/x86_64-linux-gnu/libc.so.6+0x27249)
#19 0x2aaaab5f4305 __libc_start_main
#20 0x5555580cd3ea content::RunContentProcess()
#14 0x55555a063cfc content::ContentMain()
#15 0x55555a0b5182 headless::(anonymous namespace)::RunContentMain()
#16 0x55555a0b4fbb _start
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000008 r11: 00002aaaab2a96a0
 r12: 0000000000000006 r13: 0000242e59960dc0 r14: 0000242e59960dd0 r15: 0000242e59960dd8
  di: 0000000000000617  si: 0000000000000617  bp: 00002aaaab7be200  bx: 0000000000000617
  dx: 0000000000000006  ax: 0000000000000000  cx: 0000000000000000  sp: 00002aaaab2a99e0
  ip: 00002aaaab657e2c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
headless::RunChildProcessIfNeeded()
#17 0x5555580d3f09 main
#18 0x2aaaab5f424a [end of stack trace]
Calling _exit(1). Core file will not be generated.
(/usr/lib/x86_64-linux-gnu/libc.so.6+0x27249)
#19 0x2aaaab5f4305 __libc_start_main
#20 0x5555580cd3ea _start
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000008 r11: 00002aaaab2a9680
 r12: 0000000000000006 r13: 0000222217facdc0 r14: 0000222217facdd0 r15: 0000222217facdd8
  di: 0000000000000614  si: 0000000000000614  bp: 00002aaaab7be200  bx: 0000000000000614
  dx: 0000000000000006  ax: 0000000000000000  cx: 0000000000000000  sp: 00002aaaab2a99c0
  ip: 00002aaaab657e2c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0904/134821.964496:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 1 time(s)
[0904/134822.093881:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 2 time(s)
[0904/134822.102804:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 3 time(s)
[0904/134822.120651:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 4 time(s)
[0904/134822.148631:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale 
[0904/134822.230888:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 5 time(s)
[0904/134822.274483:WARNING:gpu_process_host.cc(1274)] The GPU process has crashed 6 time(s)
[0904/134822.274611:FATAL:gpu_data_manager_impl_private.cc(407)] GPU process isn't usable. Goodbye.
#0 0x55555a37ed79 base::debug::CollectStackTrace()
#1 0x55555a2fc633 base::debug::StackTrace::StackTrace()
#2 0x55555a30c15f logging::LogMessage::~LogMessage()
#3 0x555558e68907 content::(anonymous namespace)::IntentionallyCrashBrowserForUnusableGpuProcess()
#4 0x555558e666be content::GpuDataManagerImplPrivate::FallBackToNextGpuMode()
#5 0x555558e64c53 content::GpuDataManagerImpl::FallBackToNextGpuMode()
#6 0x555558e6ef5f content::GpuProcessHost::RecordProcessCrash()
#7 0x555558cf96d3 content::BrowserChildProcessHostImpl::OnProcessLaunchFailed()
#8 0x555558d591f0 content::internal::ChildProcessLauncherHelper::PostLaunchOnClientThread()
#9 0x555558d59435 base::internal::Invoker<>::RunOnce()
#10 0x55555a342306 base::TaskAnnotator::RunTask()
#11 0x55555a353cf6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#12 0x55555a3539ea base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#13 0x55555a3a0899 base::MessagePumpLibevent::Run()
#14 0x55555a35459b base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#15 0x55555a32d9bd base::RunLoop::Run()
#16 0x555558d15f18 content::BrowserProcessSubThread::IOThreadRun()
#17 0x55555a36c874 base::Thread::ThreadMain()
#18 0x55555a38ecaa base::(anonymous namespace)::ThreadFunc()
#19 0x2aaaab656134 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x89133)
#20 0x2aaaab6d5a40 __clone
Task trace:
#0 0x555558d5905e content::internal::ChildProcessLauncherHelper::PostLaunchOnLauncherThread()
#1 0x555558d58afc content::internal::ChildProcessLauncherHelper::StartLaunchOnClientThread()
#2 0x55555928a7c2 content::VizProcessTransportFactory::ConnectHostFrameSinkManager()
#3 0x55555a9ae26f mojo::SimpleWatcher::Context::Notify()
#4 0x55555928a7c2 content::VizProcessTransportFactory::ConnectHostFrameSinkManager()
Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.

Received signal 6
#0 0x55555a37ed79 base::debug::CollectStackTrace()
#1 0x55555a2fc633 base::debug::StackTrace::StackTrace()
#2 0x55555a37e95b base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x2aaaab609050 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x3c04f)
#4 0x2aaaab657e2c (/usr/lib/x86_64-linux-gnu/libc.so.6+0x8ae2b)
#5 0x2aaaab608fb2 gsignal
#6 0x2aaaab5f3472 abort
#7 0x55555a37d8f5 base::debug::BreakDebugger()
#8 0x55555a30c5b2 logging::LogMessage::~LogMessage()
#9 0x555558e68907 content::(anonymous namespace)::IntentionallyCrashBrowserForUnusableGpuProcess()
#10 0x555558e666be content::GpuDataManagerImplPrivate::FallBackToNextGpuMode()
#11 0x555558e64c53 content::GpuDataManagerImpl::FallBackToNextGpuMode()
#12 0x555558e6ef5f content::GpuProcessHost::RecordProcessCrash()
#13 0x555558cf96d3 content::BrowserChildProcessHostImpl::OnProcessLaunchFailed()
#14 0x555558d591f0 content::internal::ChildProcessLauncherHelper::PostLaunchOnClientThread()
#15 0x555558d59435 base::internal::Invoker<>::RunOnce()
#16 0x55555a342306 base::TaskAnnotator::RunTask()
#17 0x55555a353cf6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#18 0x55555a3539ea base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#19 0x55555a3a0899 base::MessagePumpLibevent::Run()
#20 0x55555a35459b base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#21 0x55555a32d9bd base::RunLoop::Run()
#22 0x555558d15f18 content::BrowserProcessSubThread::IOThreadRun()
#23 0x55555a36c874 base::Thread::ThreadMain()
#24 0x55555a38ecaa base::(anonymous namespace)::ThreadFunc()
#25 0x2aaaab656134 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x89133)
#26 0x2aaaab6d5a40 __clone
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000008 r11: 00000000ae316e43
 r12: 0000000000000006 r13: 00002aaaae318580 r14: 00002aaaae318590 r15: 00002aaaae318598
  di: 0000000000000610  si: 000000000000061d  bp: 00002aaaae3196c0  bx: 000000000000061d
  dx: 0000000000000006  ax: 0000000000000000  cx: 0000000000000000  sp: 00002aaaae3173c0
  ip: 00002aaaab657e2c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Addressed with https://github.com/MultiQC/MultiQC/pull/2888
