### ISSUE TITLE
BBMap report

### ISSUE THREAD

**Issue by Juke34** [MultiQC/MultiQC#2866]
### Description of bug

  ╭───────────────── Oops! The 'bbmap' MultiQC module broke... ──────────────────╮
  │ Please copy this log and report it at                                        │
  │ https://github.com/ewels/MultiQC/issues                                      │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ ./yeast_R1_seqkit_clean_qhist.txt                                            │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 65 │
  │     output = mod()                                                           │
  │              ^^^^^                                                           │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/bbmap/bbmap. │
  │     if self.parse_logs(file_type, **f):                                      │
  │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/bbmap/bbmap. │
  │     line = [value_type(value) for value_type, value in zip(log_descr["cols"] │
  │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/bbmap/bbmap. │
  │     line = [value_type(value) for value_type, value in zip(log_descr["cols"] │
  │             ^^^^^^^^^^^^^^^^^                                                │
  │ ValueError: invalid literal for int() with base 10: '32.549'                 │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯

### File that triggers the error

[yeast_R1_seqkit_clean_qhist.txt](https://github.com/user-attachments/files/17056758/yeast_R1_seqkit_clean_qhist.txt)

### MultiQC Error log

```console
multiqc -p . -c multiqc_conf.yml  -v

/// MultiQC 🔍 v1.25

[2024-09-19 12:12:33] multiqc.core.tmp_dir                               [DEBUG  ]  Using new temporary directory: /var/folders/7c/qsm6f54x1dd3h9zk35v6484m0000gp/T/tmpnajsph_1
[2024-09-19 12:12:33] root                                               [DEBUG  ]  Logging to file: /var/folders/7c/qsm6f54x1dd3h9zk35v6484m0000gp/T/tmpnajsph_1/multiqc.log
[2024-09-19 12:12:33] multiqc.core.update_config                         [DEBUG  ]  This is MultiQC v1.25
[2024-09-19 12:12:33] multiqc.core.update_config                         [DEBUG  ]  Running Python 3.12.6 | packaged by conda-forge | (main, Sep 11 2024, 04:55:15) [Clang 17.0.6 ]
[2024-09-19 12:12:33] multiqc.config                                     [INFO   ]  Loading config settings from: multiqc_conf.yml
[2024-09-19 12:12:33] multiqc.config                                     [DEBUG  ]  New config: {'title': 'Nextflow Alignment pipeline', 'run_modules': ['fastqc', 'fastp', 'bbmap'], 'module_order': [{'fastqc': {'name': 'FastQC (raw)', 'path_filters': ['*raw_logs*']}}, 'fastp', {'fastqc': {'name': 'FastQC (trimmed)', 'path_filters': ['*trimmed_logs*']}}, {'bbmap': None}, {'fastqc': {'name': 'FastQC (bbmap)', 'path_filters': ['*bbmap_logs*']}}]}
[2024-09-19 12:12:33] urllib3.connectionpool                             [DEBUG  ]  Starting new HTTPS connection (1): api.multiqc.info:443
[2024-09-19 12:12:33] urllib3.connectionpool                             [DEBUG  ]  https://api.multiqc.info:443 "GET /version?version_multiqc=1.25&version_python=3.12.6&operating_system=Darwin&is_docker=False&is_singularity=False&is_conda=True&is_ci=False&is_notebook=False HTTP/11" 200 178
[2024-09-19 12:12:33] multiqc.core.version_check                         [DEBUG  ]  Latest MultiQC version is v1.25, released 2024-09-17
[2024-09-19 12:12:33] multiqc.multiqc                                    [DEBUG  ]  Working dir : /Users/jacquesdainat/git/Juke34/AliNe/debug
[2024-09-19 12:12:33] multiqc.multiqc                                    [DEBUG  ]  Template    : default
[2024-09-19 12:12:33] multiqc.multiqc                                    [DEBUG  ]  Command used: /Users/jacquesdainat/miniconda3/envs/multiqc/bin/multiqc -p . -c multiqc_conf.yml -v
[2024-09-19 12:12:33] multiqc.core.file_search                           [INFO   ]  Search path: /Users/jacquesdainat/git/Juke34/AliNe/debug
[2024-09-19 12:12:33] multiqc.core.file_search                           [INFO   ]  Only using modules: fastqc, fastp, fastqc, bbmap, fastqc
[2024-09-19 12:12:33] multiqc.core.file_search                           [DEBUG  ]  Analysing modules: fastqc, fastp, fastqc, bbmap, fastqc
[2024-09-19 12:12:33] multiqc.core.file_search                           [DEBUG  ]  Search keys: bbmap, fastp, fastqc, fastqc, fastqc, software_versions
[2024-09-19 12:12:33] multiqc.report                                     [DEBUG  ]  Ignored 319 search patterns that didn't match running modules
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 90/90  
[2024-09-19 12:12:33] multiqc.report                                     [DEBUG  ]  Summary of files that were skipped by the search: |skipped_no_match: 54|, |skipped_ignore_pattern: 2|
[2024-09-19 12:12:33] multiqc.core.exec_modules                          [DEBUG  ]  Running module: fastqc
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_illumina1.5_bbmap_logs/yeast_illumina1.5_seqkit_clean_sorted_fastqc.zip' as it didn't match the path_filters for 'FastQC (raw)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_illumina1.5_trimmed_logs/yeast_illumina1.5_seqkit_clean_fastqc.zip' as it didn't match the path_filters for 'FastQC (raw)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_R1_trimmed_logs/yeast_R1_seqkit_clean_fastqc.zip' as it didn't match the path_filters for 'FastQC (raw)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_R1_bbmap_logs/yeast_R1_seqkit_clean_sorted_fastqc.zip' as it didn't match the path_filters for 'FastQC (raw)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_R2_trimmed_logs/yeast_R2_seqkit_clean_fastqc.zip' as it didn't match the path_filters for 'FastQC (raw)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_R2_bbmap_logs/yeast_R2_seqkit_clean_sorted_fastqc.zip' as it didn't match the path_filters for 'FastQC (raw)'
[2024-09-19 12:12:33] multiqc.core.exec_modules                          [DEBUG  ]  No samples found: fastqc
[2024-09-19 12:12:33] multiqc.core.exec_modules                          [DEBUG  ]  Running module: fastqc
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_illumina1.5_bbmap_logs/yeast_illumina1.5_seqkit_clean_sorted_fastqc.zip' as it didn't match the path_filters for 'FastQC (trimmed)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Selecting 'fastqc_yeast_illumina1.5_trimmed_logs/yeast_illumina1.5_seqkit_clean_fastqc.zip' as it matched the path_filters for 'FastQC (trimmed)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Selecting 'fastqc_yeast_R1_trimmed_logs/yeast_R1_seqkit_clean_fastqc.zip' as it matched the path_filters for 'FastQC (trimmed)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_R1_bbmap_logs/yeast_R1_seqkit_clean_sorted_fastqc.zip' as it didn't match the path_filters for 'FastQC (trimmed)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Selecting 'fastqc_yeast_R2_trimmed_logs/yeast_R2_seqkit_clean_fastqc.zip' as it matched the path_filters for 'FastQC (trimmed)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_R2_bbmap_logs/yeast_R2_seqkit_clean_sorted_fastqc.zip' as it didn't match the path_filters for 'FastQC (trimmed)'
[2024-09-19 12:12:33] multiqc.modules.fastqc.fastqc                      [INFO   ]  Found 3 reports
[2024-09-19 12:12:33] multiqc.report                                     [DEBUG  ]  Wrote data file multiqc_fastqc.txt
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc-1: deleting attribute self.sample_names
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc-1: deleting attribute self.order_of_duplication_levels
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc-1: deleting attribute self.status_colours
[2024-09-19 12:12:33] multiqc.core.exec_modules                          [DEBUG  ]  Running module: bbmap
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R2_seqkit_clean_bhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found bhist output for sample yeast_R2_seqkit_clean_bhist with 125 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_bhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found bhist output for sample yeast_R1_seqkit_clean_bhist with 125 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_illumina1.5_seqkit_clean_bhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found bhist output for sample yeast_illumina1.5_seqkit_clean_bhist with 51 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R2_seqkit_clean_ehist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found ehist output for sample yeast_R2_seqkit_clean_ehist with 12 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_ehist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found ehist output for sample yeast_R1_seqkit_clean_ehist with 16 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_illumina1.5_seqkit_clean_ehist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found ehist output for sample yeast_illumina1.5_seqkit_clean_ehist with 3 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_illumina1.5_seqkit_clean_gchist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found gchist output for sample yeast_illumina1.5_seqkit_clean_gchist with 101 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R2_seqkit_clean_gchist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found gchist output for sample yeast_R2_seqkit_clean_gchist with 101 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_gchist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found gchist output for sample yeast_R1_seqkit_clean_gchist with 101 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_illumina1.5_seqkit_clean_idhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found idhist output for sample yeast_illumina1.5_seqkit_clean_idhist with 101 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_idhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found idhist output for sample yeast_R1_seqkit_clean_idhist with 101 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R2_seqkit_clean_idhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found idhist output for sample yeast_R2_seqkit_clean_idhist with 101 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_illumina1.5_seqkit_clean_ihist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [WARNING]  File yeast_illumina1.5_seqkit_clean_ihist.txt appears to contain no data for plotting, ignoring...
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_ihist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [WARNING]  File yeast_R1_seqkit_clean_ihist.txt appears to contain no data for plotting, ignoring...
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R2_seqkit_clean_ihist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [WARNING]  File yeast_R2_seqkit_clean_ihist.txt appears to contain no data for plotting, ignoring...
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_indelhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found indelhist output for sample yeast_R1_seqkit_clean_indelhist with 14 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_illumina1.5_seqkit_clean_indelhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [WARNING]  File yeast_illumina1.5_seqkit_clean_indelhist.txt appears to contain no data for plotting, ignoring...
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R2_seqkit_clean_indelhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found indelhist output for sample yeast_R2_seqkit_clean_indelhist with 5 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R2_seqkit_clean_lhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found lhist output for sample yeast_R2_seqkit_clean_lhist with 102 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_lhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found lhist output for sample yeast_R1_seqkit_clean_lhist with 1 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_illumina1.5_seqkit_clean_lhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found lhist output for sample yeast_illumina1.5_seqkit_clean_lhist with 1 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_qahist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Found qahist output for sample yeast_R1_seqkit_clean_qahist with 42 rows
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [DEBUG  ]  Parsing ./yeast_R1_seqkit_clean_qhist.txt
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [ERROR  ]  Expected key value pair in ./yeast_R1_seqkit_clean_qhist:2 but found '['BaseNum', 'Read1_linear', 'Read1_log', 'Read1_measured']'
[2024-09-19 12:12:33] multiqc.modules.bbmap.bbmap                        [ERROR  ]  Table header should begin with 'Quality'
╭──────────────────────────────────────────────── Oops! The 'bbmap' MultiQC module broke... ─────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                            │
│ Please attach a file that triggers the error. The last file found was: ./yeast_R1_seqkit_clean_qhist.txt                                   │
│                                                                                                                                            │
│ Traceback (most recent call last):                                                                                                         │
│   File "/Users/jacquesdainat/miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/core/exec_modules.py", line 68, in exec_modules  │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                │
│                                                                        ^^^^^^^^^^^^^^^^^^^^                                                │
│   File "/Users/jacquesdainat/miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/modules/bbmap/bbmap.py", line 77, in __init__    │
│     if self.parse_logs(file_type, **f):                                                                                                    │
│        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                     │
│   File "/Users/jacquesdainat/miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/modules/bbmap/bbmap.py", line 195, in parse_logs │
│     line = [value_type(value) for value_type, value in zip(log_descr["cols"].values(), line)]                                              │
│             ^^^^^^^^^^^^^^^^^                                                                                                              │
│ ValueError: invalid literal for int() with base 10: '32.549'                                                                               │
│                                                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[2024-09-19 12:12:33] multiqc.core.exec_modules                          [DEBUG  ]  Oops! The 'bbmap' MultiQC module broke...
================================================================================
Traceback (most recent call last):
  File "/Users/jacquesdainat/miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/core/exec_modules.py", line 68, in exec_modules
    these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()
                                                                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacquesdainat/miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/modules/bbmap/bbmap.py", line 77, in __init__
    if self.parse_logs(file_type, **f):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacquesdainat/miniconda3/envs/multiqc/lib/python3.12/site-packages/multiqc/modules/bbmap/bbmap.py", line 195, in parse_logs
    line = [value_type(value) for value_type, value in zip(log_descr["cols"].values(), line)]
            ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '32.549'
================================================================================
[2024-09-19 12:12:33] multiqc.core.exec_modules                          [DEBUG  ]  Running module: fastqc
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Selecting 'fastqc_yeast_illumina1.5_bbmap_logs/yeast_illumina1.5_seqkit_clean_sorted_fastqc.zip' as it matched the path_filters for 'FastQC (bbmap)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_illumina1.5_trimmed_logs/yeast_illumina1.5_seqkit_clean_fastqc.zip' as it didn't match the path_filters for 'FastQC (bbmap)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_R1_trimmed_logs/yeast_R1_seqkit_clean_fastqc.zip' as it didn't match the path_filters for 'FastQC (bbmap)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Selecting 'fastqc_yeast_R1_bbmap_logs/yeast_R1_seqkit_clean_sorted_fastqc.zip' as it matched the path_filters for 'FastQC (bbmap)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Skipping 'fastqc_yeast_R2_trimmed_logs/yeast_R2_seqkit_clean_fastqc.zip' as it didn't match the path_filters for 'FastQC (bbmap)'
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc/zip - Selecting 'fastqc_yeast_R2_bbmap_logs/yeast_R2_seqkit_clean_sorted_fastqc.zip' as it matched the path_filters for 'FastQC (bbmap)'
[2024-09-19 12:12:33] multiqc.modules.fastqc.fastqc                      [INFO   ]  Found 3 reports
[2024-09-19 12:12:33] multiqc.report                                     [DEBUG  ]  Wrote data file multiqc_fastqc_1.txt
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc-2: deleting attribute self.sample_names
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc-2: deleting attribute self.order_of_duplication_levels
[2024-09-19 12:12:33] multiqc.base_module                                [DEBUG  ]  fastqc-2: deleting attribute self.status_colours
[2024-09-19 12:12:33] multiqc.core.software_versions                     [DEBUG  ]  Reading software versions from config.software_versions
[2024-09-19 12:12:33] multiqc.core.file_search                           [INFO   ]  Only using modules: fastqc, fastqc
[2024-09-19 12:12:33] multiqc.report                                     [DEBUG  ]  Wrote data file multiqc_software_versions.txt
[2024-09-19 12:12:33] multiqc.core.write_results                         [INFO   ]  Rendering plots. Export plots to formats png, svg, pdf is requested, so it might take a while. To disable plot export, set `export_plots: false` in config, or remove the `--export-plots` command line flag
   rendering plots | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 25/25  
[2024-09-19 12:12:41] multiqc.report                                     [DEBUG  ]  Wrote data file multiqc_general_stats.txt
[2024-09-19 12:12:42] multiqc.core.write_results                         [INFO   ]  Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
[2024-09-19 12:12:42] multiqc.core.write_results                         [DEBUG  ]  Exporting plot data to files
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_sequence_counts_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_per_base_sequence_quality_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_per_sequence_quality_scores_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_per_sequence_gc_content_plot_Percentages.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_per_sequence_gc_content_plot_Counts.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_per_base_n_content_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc_sequence_length_distribution_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_sequence_duplication_levels_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_overrepresented_sequences_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_top_overrepresented_sequences_table.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1_adapter_content_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-1-status-check-heatmap.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_sequence_counts_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_per_base_sequence_quality_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_per_sequence_quality_scores_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_per_sequence_gc_content_plot_Percentages.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_per_sequence_gc_content_plot_Counts.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_per_base_n_content_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc_sequence_length_distribution_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_sequence_duplication_levels_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_overrepresented_sequences_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_top_overrepresented_sequences_table.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2_adapter_content_plot.txt
[2024-09-19 12:12:42] multiqc.report                                     [DEBUG  ]  Wrote data file fastqc-2-status-check-heatmap.txt
[2024-09-19 12:12:42] multiqc.core.write_results                         [DEBUG  ]  Moving data file from '/var/folders/7c/qsm6f54x1dd3h9zk35v6484m0000gp/T/tmpnajsph_1/multiqc_data' to '/Users/jacquesdainat/git/Juke34/AliNe/debug/Nextflow-Alignment-pipeline_multiqc_report_data_1'
[2024-09-19 12:12:42] multiqc.core.write_results                         [INFO   ]  Data        : Nextflow-Alignment-pipeline_multiqc_report_data_1
[2024-09-19 12:12:42] multiqc.core.write_results                         [DEBUG  ]  Compressing plot data
[2024-09-19 12:12:42] multiqc.core.write_results                         [INFO   ]  Report      : Nextflow-Alignment-pipeline_multiqc_report_1.html
[2024-09-19 12:12:42] multiqc.core.write_results                         [DEBUG  ]  Moving plots directory from '/var/folders/7c/qsm6f54x1dd3h9zk35v6484m0000gp/T/tmpnajsph_1/multiqc_plots' to '/Users/jacquesdainat/git/Juke34/AliNe/debug/Nextflow-Alignment-pipeline_multiqc_report_plots_1'
[2024-09-19 12:12:42] multiqc.core.write_results                         [INFO   ]  Plots       : Nextflow-Alignment-pipeline_multiqc_report_plots_1
[2024-09-19 12:12:42] multiqc.core.write_results                         [DEBUG  ]  Report HTML written to /Users/jacquesdainat/git/Juke34/AliNe/debug/Nextflow-Alignment-pipeline_multiqc_report_1.html
[2024-09-19 12:12:42] multiqc.multiqc                                    [INFO   ]  MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by SoldierFace** [comment]
download
https://bit.ly/3XQLHlH

you may need to install the c compiler
