### ISSUE TITLE
V1.25 in conda end up properly but not in the container distributed by biocontainers

### ISSUE THREAD

**Issue by Juke34** [MultiQC/MultiQC#2867]
### Description of bug

Related to #2866 
Runing the same case in the container (quay.io/biocontainers/multiqc:1.25--pyhdfd78af_0)
After the `MultiQC complete` message the prompt does not come back. 
So MultiQC is frozen, I guess is not ending the process properly...

### File that triggers the error

[yeast_R1_seqkit_clean_qhist.txt](https://github.com/user-attachments/files/17057475/yeast_R1_seqkit_clean_qhist.txt)

### MultiQC Error log

```console
# multiqc -p . -c multiqc_conf.yml

/// MultiQC 🔍 v1.25

            config | Loading config settings from: multiqc_conf.yml
       file_search | Search path: /work
       file_search | Only using modules: fastqc, fastp, fastqc, bbmap, fastqc
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 200/200  
            fastqc | Found 3 reports
             bbmap | File yeast_illumina1.5_seqkit_clean_ihist.txt appears to contain no data for plotting, ignoring...
             bbmap | File yeast_R1_seqkit_clean_ihist.txt appears to contain no data for plotting, ignoring...
             bbmap | File yeast_R2_seqkit_clean_ihist.txt appears to contain no data for plotting, ignoring...
             bbmap | File yeast_illumina1.5_seqkit_clean_indelhist.txt appears to contain no data for plotting, ignoring...
             bbmap | Expected key value pair in ./yeast_R1_seqkit_clean_qhist:2 but found '['BaseNum', 'Read1_linear', 'Read1_log', 'Read1_measured']'
             bbmap | Table header should begin with 'Quality'
╭─────────────────────────────── Oops! The 'bbmap' MultiQC module broke... ────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                          │
│ Please attach a file that triggers the error. The last file found was: ./yeast_R1_seqkit_clean_qhist.txt │
│                                                                                                          │
│ Traceback (most recent call last):                                                                       │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/core/exec_modules.py", line 68, in exec_modules  │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()              │
│                                                                        ^^^^^^^^^^^^^^^^^^^^              │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/bbmap/bbmap.py", line 77, in __init__    │
│     if self.parse_logs(file_type, **f):                                                                  │
│        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                   │
│   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/bbmap/bbmap.py", line 195, in parse_logs │
│     line = [value_type(value) for value_type, value in zip(log_descr["cols"].values(), line)]            │
│             ^^^^^^^^^^^^^^^^^                                                                            │
│ ValueError: invalid literal for int() with base 10: '32.549'                                             │
│                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
            fastqc | Found 3 reports
       file_search | Only using modules: fastqc, fastqc
     write_results | Rendering plots. Export plots to formats png, svg, pdf is requested, so it might take a while. To disable plot export, set `export_plots: false` in config, or remove the `--export-plots` command line flag
 ⠼ rendering plots | ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   4% 1/25 FastQC (trimmed)/Sequence Counts              plot | fastqc-1_sequence_counts_plot-pct: Unable to export plot to PDF image. Function did not complete in 60 seconds
              plot | Unable to export plot to flat images: fastqc-1_sequence_counts_plot
              plot | Unable to export plot to flat images: fastqc-1_per_base_sequence_quality_plot
              plot | Unable to export plot to flat images: fastqc-1_per_sequence_quality_scores_plot
              plot | Unable to export plot to flat images: fastqc-1_per_sequence_gc_content_plot
              plot | Unable to export plot to flat images: fastqc-1_per_base_n_content_plot
 ⠦ rendering plots | ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━  28% 7/25 FastQC (trimmed)/Sequence Length Distribution              plot | Unable to export plot to flat images: fastqc_sequence_length_distribution_plot
              plot | Unable to export plot to flat images: fastqc-1_sequence_duplication_levels_plot
              plot | Unable to export plot to flat images: fastqc-1_overrepresented_sequences_plot
              plot | Unable to export plot to flat images: fastqc-1_top_overrepresented_sequences_table
              plot | Unable to export plot to flat images: fastqc-1_adapter_content_plot
              plot | Unable to export plot to flat images: fastqc-1-status-check-heatmap
              plot | Unable to export plot to flat images: fastqc-2_sequence_counts_plot
              plot | Unable to export plot to flat images: fastqc-2_per_base_sequence_quality_plot
              plot | Unable to export plot to flat images: fastqc-2_per_sequence_quality_scores_plot
              plot | Unable to export plot to flat images: fastqc-2_per_sequence_gc_content_plot
              plot | Unable to export plot to flat images: fastqc-2_per_base_n_content_plot
              plot | Unable to export plot to flat images: fastqc_sequence_length_distribution_plot
              plot | Unable to export plot to flat images: fastqc-2_sequence_duplication_levels_plot
              plot | Unable to export plot to flat images: fastqc-2_overrepresented_sequences_plot
 ⠧ rendering plots | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━  88% 22/25 FastQC (bbmap)/Top overrepresented sequences              plot | Unable to export plot to flat images: fastqc-2_top_overrepresented_sequences_table
              plot | Unable to export plot to flat images: fastqc-2_adapter_content_plot
              plot | Unable to export plot to flat images: fastqc-2-status-check-heatmap
   rendering plots | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 25/25  
              plot | Unable to export plot to flat images: general_stats_table
     write_results | Existing reports found, adding suffix to filenames. Use '--force' to overwrite.
     write_results | Data        : Nextflow-Alignment-pipeline_multiqc_report_data_1_2
     write_results | Report      : Nextflow-Alignment-pipeline_multiqc_report_2.html
     write_results | Plots       : Nextflow-Alignment-pipeline_multiqc_report_plots_1_2
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by SneakPeak2003** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by vladsavelyev** [comment]
Would you be able to share the `multiqc_conf.yml` used for the container run? 
What OS are you running?

There is a known problem running in a linux container on MacOS ARM with `explort_plots: True` in config: https://github.com/MultiQC/MultiQC/issues/2667

**Comment by Juke34** [comment]
Yes I'm running on M2 (ARM).
But I have not set this option, is it set by default?

I can share multiqc_conf.yml if still needed.

**Comment by vladsavelyev** [comment]
Please share the config, as well as the log that you are having when running in a container, and the container name. Essentially, everything needed to reproduce the issue. That would really help a lot!

**Comment by vladsavelyev** [comment]
Probably addressed with https://github.com/MultiQC/MultiQC/pull/2888
