### ISSUE TITLE
Docker image failes to build

### ISSUE THREAD

**Issue by jchorl** [MultiQC/MultiQC#2884]
### Description of bug

Error building dockerfile:
```
 => ERROR [14/14] RUN echo "Docker build log: Testing multiqc" 1>&2 &&     multiqc --help                                 0.6s
------                                                                                                                         
 > [14/14] RUN echo "Docker build log: Testing multiqc" 1>&2 &&     multiqc --help:                                            
0.129 Docker build log: Testing multiqc                                                                                        
0.598 Traceback (most recent call last):                                                                                       
0.598   File "/usr/local/bin/multiqc", line 5, in <module>                                                                     
0.598     from multiqc.__main__ import run_multiqc
0.598   File "/usr/local/lib/python3.12/site-packages/multiqc/__init__.py", line 22, in <module>
0.598     from multiqc import (  # noqa: E402
0.598   File "/usr/local/lib/python3.12/site-packages/multiqc/report.py", line 21, in <module>
0.598     from tkinter import N
0.598   File "/usr/local/lib/python3.12/tkinter/__init__.py", line 38, in <module>
0.599     import _tkinter # If this fails your Python may not be configured for Tk
0.599     ^^^^^^^^^^^^^^^
0.599 ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
------

 1 warning found (use docker --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 59)
Dockerfile:55
--------------------
  54 |     # Check everything is working smoothly
  55 | >>> RUN echo "Docker build log: Testing multiqc" 1>&2 && \
  56 | >>>     multiqc --help 
  57 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c echo \"Docker build log: Testing multiqc\" 1>&2 &&     multiqc --help" did not complete successfully: exit code: 1
```

`apt-get` installing `tk` fixes this. Searching the stack trace and git blaming, looks like this dep was added today.

```
63314cc2a multiqc/report.py       (Vlad Savelyev   2024-09-26 12:41:48 +0200   21) from tkinter import N
```

Is there a CI test to make sure the docker image builds?

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
> Is there a CI test to make sure the docker image builds?

Yep, https://github.com/MultiQC/MultiQC/actions/workflows/docker.yml - and it recently started failing. Went unnoticed because it builds only on push to main, but not on PR. Good catch - will fix and will make it test-build on PR commits as well.

**Comment by vladsavelyev** [comment]
Fixed!

**Comment by jchorl** [comment]
> Fixed!

Thank you!
