### ISSUE TITLE
Cutadapt module broke

### ISSUE THREAD

**Issue by srisarya** [MultiQC/MultiQC#2924]
### Description of bug

Multiqc says that there is a .json file which triggers an error.

### File that triggers the error

[demux_Ni5_007.json](https://github.com/user-attachments/files/17436072/demux_Ni5_007.json)

### MultiQC Error log

```console
multiqc .

/// MultiQC 🔍 v1.25.1

       file_search | Search path: /data/scratch/bty636/demultiplexing_both_q10_e3
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 520/520
╭────────────────────────────────────────────── Oops! The 'cutadapt' MultiQC module broke... ───────────────────────────────────────────────╮                        
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                           │                        
│ Please attach a file that triggers the error. The last file found was: ./demux_Ni5_007.json                                               │                        
│                                                                                                                                           │                        
│ Traceback (most recent call last):                                                                                                        │                        
│   File "/data/home/bty636/.conda/envs/multiqc/lib/python3.13/site-packages/multiqc/core/exec_modules.py", line 68, in exec_modules        │                        
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                               │                        
│                                                                        ~~~~~~~~~~~~~~~~~~^^                                               │                        
│   File "/data/home/bty636/.conda/envs/multiqc/lib/python3.13/site-packages/multiqc/modules/cutadapt/cutadapt.py", line 55, in __init__    │                        
│     self.parse_file(f)                                                                                                                    │                        
│     ~~~~~~~~~~~~~~~^^^                                                                                                                    │                        
│   File "/data/home/bty636/.conda/envs/multiqc/lib/python3.13/site-packages/multiqc/modules/cutadapt/cutadapt.py", line 81, in parse_file  │                        
│     self.parse_json(f)                                                                                                                    │                        
│     ~~~~~~~~~~~~~~~^^^                                                                                                                    │                        
│   File "/data/home/bty636/.conda/envs/multiqc/lib/python3.13/site-packages/multiqc/modules/cutadapt/cutadapt.py", line 131, in parse_json │                        
│     s_name = SampleName(self.clean_s_name([v for k, v in data["input"].items() if k.startswith("path")], f=f))                            │                        
│                         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                             │                        
│   File "/data/home/bty636/.conda/envs/multiqc/lib/python3.13/site-packages/multiqc/base_module.py", line 724, in clean_s_name             │                        
│     self.clean_s_name(                                                                                                                    │                        
│     ~~~~~~~~~~~~~~~~~^                                                                                                                    │                        
│         sn,                                                                                                                               │                        
│         ^^^                                                                                                                               │                        
│     ...<6 lines>...                                                                                                                       │                        
│         prepend_dirs=prepend_dirs,                                                                                                        │                        
│         ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                        │                        
│     )                                                                                                                                     │                        
│     ^                                                                                                                                     │                        
│   File "/data/home/bty636/.conda/envs/multiqc/lib/python3.13/site-packages/multiqc/base_module.py", line 784, in clean_s_name             │                        
│     trimmed_name = SampleName(os.path.basename(trimmed_name))                                                                             │                        
│                               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^                                                                              │                        
│   File "<frozen posixpath>", line 167, in basename                                                                                        │                        
│ TypeError: expected str, bytes or os.PathLike object, not NoneType                                                                        │                        
│                                                                                                                                           │                        
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                        
            fastqc | Found 169 reports
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this issue, and thanks a lot for reporting! Fixed with https://github.com/MultiQC/MultiQC/pull/2936
