### ISSUE TITLE
bug: Import of qualimap Results - could not convert string to float: '∞'

### ISSUE THREAD

**Issue by KuechlerO** [MultiQC/MultiQC#2931]
### Description of bug

I have QualiMap reports created by QualiMap v.2.3.

One special report was created which includes in the `rnaseq_qc_results.txt` the lines: 
```
>>>>>>> Transcript coverage profile

    5' bias = 0,06
    3' bias = 0
    5'-3' bias = ∞
```

This causes `MultiQC` to throw the following error when being applied:
```

          __init__ | Couldn't determine decimal separator for file output/module1_qc_preproc_and_alignment/output/qualimap/star/18-5085/rnaseq_qc_results.txt, as both . and , are found in a rational value: 3.386,73
╭───────────────────────────────────────────────────────── Oops! The 'qualimap' MultiQC module broke... ──────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                 │
│ Please attach a file that triggers the error. The last file found was:                                                                                          │
│ output/module1_qc_preproc_and_alignment/output/qualimap/star/19-5325_2/rnaseq_qc_results.txt                                                                    │
│                                                                                                                                                                 │
│ Traceback (most recent call last):                                                                                                                              │
│   File "/shares/diska/snakesplice/.snakemake/conda/cd597c1d89201b285bbb8b220dd9d685_/lib/python3.12/site-packages/multiqc/core/exec_modules.py", line 68, in ex │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                                     │
│                                                                        ^^^^^^^^^^^^^^^^^^^^                                                                     │
│   File "/shares/diska/snakesplice/.snakemake/conda/cd597c1d89201b285bbb8b220dd9d685_/lib/python3.12/site-packages/multiqc/modules/qualimap/qualimap.py", line 7 │
│     n["RNASeq"] = QM_RNASeq.parse_reports(self)                                                                                                                 │
│                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 │
│   File "/shares/diska/snakesplice/.snakemake/conda/cd597c1d89201b285bbb8b220dd9d685_/lib/python3.12/site-packages/multiqc/modules/qualimap/QM_RNASeq.py", line  │
│     d = parse_numerals(                                                                                                                                         │
│         ^^^^^^^^^^^^^^^                                                                                                                                         │
│   File "/shares/diska/snakesplice/.snakemake/conda/cd597c1d89201b285bbb8b220dd9d685_/lib/python3.12/site-packages/multiqc/modules/qualimap/__init__.py", line 9 │
│     d[rate_metrics[k]] = float(v)                                                                                                                               │
│                          ^^^^^^^^                                                                                                                               │
│ ValueError: could not convert string to float: '∞'                                                                                                              │
│                                                                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

1. Main error:
 There seems to be a problem for MultiQC, when parsing '∞'.
 
 2. Side error:
 The `__init__` error is actually caused by another qualimap report that includes the following
 ```
 >>>>>>> Transcript coverage profile

    5' bias = 0,04
    3' bias = 0
    5'-3' bias = 3.386,73
```
 However, seems like it might only be a warning and does not prevent `MultiQC` from further processing.

### MultiQC Error log

```console
/// MultiQC 🔍 v1.25.1

     update_config | Prepending directory to sample names
       file_search | Search path: [... <skipped this part to shorten log>]

          __init__ | Couldn't determine decimal separator for file output/module1_qc_preproc_and_alignment/output/qualimap/star/18-5085/rnaseq_qc_results.txt, as both . and , are found in a rational value: 3.386,73
╭───────────────────────────────────────────────────────── Oops! The 'qualimap' MultiQC module broke... ──────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                 │
│ Please attach a file that triggers the error. The last file found was:                                                                                          │
│ output/module1_qc_preproc_and_alignment/output/qualimap/star/19-5325_2/rnaseq_qc_results.txt                                                                    │
│                                                                                                                                                                 │
│ Traceback (most recent call last):                                                                                                                              │
│   File "/shares/diska/snakesplice/.snakemake/conda/cd597c1d89201b285bbb8b220dd9d685_/lib/python3.12/site-packages/multiqc/core/exec_modules.py", line 68, in ex │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                                     │
│                                                                        ^^^^^^^^^^^^^^^^^^^^                                                                     │
│   File "/shares/diska/snakesplice/.snakemake/conda/cd597c1d89201b285bbb8b220dd9d685_/lib/python3.12/site-packages/multiqc/modules/qualimap/qualimap.py", line 7 │
│     n["RNASeq"] = QM_RNASeq.parse_reports(self)                                                                                                                 │
│                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 │
│   File "/shares/diska/snakesplice/.snakemake/conda/cd597c1d89201b285bbb8b220dd9d685_/lib/python3.12/site-packages/multiqc/modules/qualimap/QM_RNASeq.py", line  │
│     d = parse_numerals(                                                                                                                                         │
│         ^^^^^^^^^^^^^^^                                                                                                                                         │
│   File "/shares/diska/snakesplice/.snakemake/conda/cd597c1d89201b285bbb8b220dd9d685_/lib/python3.12/site-packages/multiqc/modules/qualimap/__init__.py", line 9 │
│     d[rate_metrics[k]] = float(v)                                                                                                                               │
│                          ^^^^^^^^                                                                                                                               │
│ ValueError: could not convert string to float: '∞'                                                                                                              │
│                                                                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
          bamtools | Found 101 bamtools stats reports
              star | Found 101 gene count files
            kraken | Found 101 reports
            fastqc | Found 400 reports

     write_results | Data        : None
     write_results | Report      : output/module1_qc_preproc_and_alignment/output/multiqc/westhafen_all/multiqc.html
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [ ] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thanks for reporting this issue! Fixed with https://github.com/MultiQC/MultiQC/pull/2937
