### ISSUE TITLE
 Oops! The 'fastqc' MultiQC module broke...

### ISSUE THREAD

**Issue by remygatins** [MultiQC/MultiQC#2982]
### Description of bug

I'm trying to run multiqc on my fastqc files and I'm getting the following error:

```bash
(/work/gatins/programs/multiqc) [r.gatins@d3037 fastqc]$ multiqc .
/work/gatins/programs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/utils/config.py:44: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/work/gatins/programs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/utils/config.py:50: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]          fastqc : Found 236 reports
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/work/gatins/programs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/work/gatins/programs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 91, in __init__
    self.fastqc_general_stats()
  File "/work/gatins/programs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 200, in fastqc_general_stats
    'avg_sequence_length': bs['avg_sequence_length'],
KeyError: 'avg_sequence_length'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
(/work/gatins/programs/multiqc) [r.gatins@d3037 fastqc]$ conda deactivate
(/shared/centos7/miniconda3/pyrosetta-072020) [r.gatins@d3037 fastqc]$ module load multiqc
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'multiqc'
```

I updated to the latest multiqc just in case but I get the same error. Multiqc was updated using conda. 

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
This seems to be using MultiQC `v1.0.dev0`. Note that we no longer support Python 2.7 either.

Could you try installing it into a clean Python 3 environment?
