### ISSUE TITLE
Preseq TypeError

### ISSUE THREAD

**Issue by guidohooiveld** [MultiQC/MultiQC#3037]
### Description of bug

I am getting an error when the output of `preseq` is being parsed. I am using the latest version of `MultiQC` (`v1.27.dev0`), but the error also occurs with `v1.26`.

Yet, it works when reverting back to `v1.25.2`.

I have attached a ZIP containing the `preseq` output for one sample (the one mentioned in the error), as well as a concatenated summary file for all samples.

The latter is generated per:  https://github.com/MultiQC/MultiQC/blob/35555b12abf83ef1f2f44f03745243c3b16512e6/multiqc/modules/preseq/preseq.py#L61-L79

Could you please have a look at this?

Thanks,
G

NB: although not related to the reported `preseq` issue, also note the _warning_ at the validation step that is triggered with the `fastp` output when using `1.27.dev0`, but not with `1.26` nor `1.25.2`...??

`preseq` command:

```
# lines of code in script used to run preseq.
$preseqpath/preseq c_curve -P "${F11}".bed -output $fn2.c_curve.txt -D &
$preseqpath/preseq lc_extrap -P "${F11}".bed -output $fn2.lc_extrap.txt -D
```

### File that triggers the error

[preseqerror.zip](https://github.com/user-attachments/files/18281995/preseqerror.zip)

### MultiQC Error log

```console
## using latest version:
## gives ERROR

$ pip install --user --upgrade --force-reinstall git+https://github.com/MultiQC/MultiQC.git


guidoh@localhost:/mnt/files/guido$ multiqc ./data_out --filename QC_report_liver.html --title "QC report mouse liver samples" --export --force


/// MultiQC 🎄 v1.27.dev0

            config | Loading config settings from: multiqc_config.yaml
     update_config | Report title: QC report mouse liver samples
       file_search | Search path: /mnt/files/guido/data_out
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 4430/4430  
            preseq | Found 36 reports
╭──────────────────────────────────────────────────────────────────── Oops! The 'preseq' MultiQC module broke... ─────────────────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                                     │
│ Please attach a file that triggers the error. The last file found was:                                                                                                              │
│ data_out/STAR_out/HTMLNDRX2_105485-001-009_AGTGACCT-CTCCTAGA_L001/HTMLNDRX2_105485-001-009_AGTGACCT-CTCCTAGA_L001_Aligned.sortedByCoord.out.bam.c_curve.txt                         │
│                                                                                                                                                                                     │
│ Traceback (most recent call last):                                                                                                                                                  │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/core/exec_modules.py", line 68, in exec_modules                                                                    │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                                                         │
│                                                                        ~~~~~~~~~~~~~~~~~~^^                                                                                         │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/modules/preseq/preseq.py", line 132, in __init__                                                                   │
│     self._make_preseq_length_trimmed_plot(reads_data, False)                                                                                                                        │
│     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^                                                                                                                        │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/modules/preseq/preseq.py", line 148, in _make_preseq_length_trimmed_plot                                           │
│     d_cnts = {sn: _modify_raw_data(sample_data, is_basepairs) for sn, sample_data in data_raw.items()}                                                                              │
│                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                       │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/modules/preseq/preseq.py", line 302, in _modify_raw_data                                                           │
│     return {_modify_raw_val(x, is_basepairs): _modify_raw_val(y, is_basepairs) for x, y in sample_data.items()}                                                                     │
│                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^                                                                                                      │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/modules/preseq/preseq.py", line 309, in _modify_raw_val                                                            │
│     return float(val) * (config.base_count_multiplier if is_basepairs else config.read_count_multiplier)                                                                            │
│            ~~~~~^^^^^                                                                                                                                                               │
│ TypeError: float() argument must be a string or a real number, not 'NoneType'                                                                                                       │
│                                                                                                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
             rseqc | Found 36 read_distribution reports
             rseqc | Found 36 gene_body_coverage reports
             rseqc | Found 36 inner_distance reports
             rseqc | Found 36 read_duplication reports
             rseqc | Found 36 junction_annotation reports
             rseqc | Found 36 junction_saturation reports
             rseqc | Found 36 infer_experiment reports
             rseqc | Found 36 bam_stat reports
             rseqc | Found 36 tin reports
            picard | Found 36 InsertSizeMetrics reports
            picard | Found 36 MarkDuplicates reports
            picard | Found 36 RnaSeqMetrics reports
          samtools | Found 36 stats reports
          samtools | Found 36 flagstat reports
          samtools | Found 36 idxstats reports
            salmon | Found 36 meta reports
            salmon | Found 36 fragment length distributions
            salmon | Found 36 library format counts reports
              star | Found 36 reports and 36 gene count files
             fastp | Found 18 reports
        validation | fastp/fastp.py: warnings while parsing barplot.pconfig[id='fastp_filtered_reads_plot'] {id: fastp_filtered_reads_plot, title: Fastp: Filtered Reads, ylab: # Reads, cpswitch_counts_label: Number of Reads, hide_empty: False}:
• 'hide_empty': unrecognized field. Available fields: id, title, anchor, height, width, square, logswitch, logswitch_active, logswitch_label, cpswitch, cpswitch_c_active, cpswitch_counts_label, cpswitch_percent_label, xlog, ylog, data_labels, xlab, ylab, xsuffix, ysuffix, tt_suffix, xlab_format, ylab_format, tt_label, x_decimals, y_decimals, tt_decimals, xmin, xmax, ymin, ymax, x_clipmin, x_clipmax, y_clipmin, y_clipmax, save_data_file, showlegend, x_minrange, y_minrange, x_bands, y_bands, x_lines, y_lines, stacking, hide_zero_cats, sort_samples, use_legend, suffix, lab_format
            fastqc | Found 72 reports
     write_results | Rendering plots. Export plots to formats png, svg, pdf is requested, so it might take a while. To disable plot export, set `export_plots: false` in config, or remove the `--export-plots` command line flag
name='Theoretical GC Content' pairs=[(0.0, 0.0), (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0), (5.0, 0.0), (6.0, 0.0), (7.0, 0.0), (8.0, 0.0), (9.0, 0.001), (10.0, 0.001), (11.0, 
0.001), (12.0, 0.002), (13.0, 0.003), (14.0, 0.005), (15.0, 0.008), (16.0, 0.013), (17.0, 0.022), (18.0, 0.036), (19.0, 0.055), (20.0, 0.082), (21.0, 0.118), (22.0, 0.164), (23.0, 
0.218), (24.0, 0.283), (25.0, 0.358), (26.0, 0.442), (27.0, 0.529), (28.0, 0.633), (29.0, 0.738), (30.0, 0.854), (31.0, 0.976), (32.0, 1.109), (33.0, 1.256), (34.0, 1.413), (35.0, 
1.584), (36.0, 1.761), (37.0, 1.942), (38.0, 2.135), (39.0, 2.326), (40.0, 2.52), (41.0, 2.718), (42.0, 2.925), (43.0, 3.132), (44.0, 3.333), (45.0, 3.51), (46.0, 3.676), (47.0, 
3.801), (48.0, 3.904), (49.0, 3.965), (50.0, 3.998), (51.0, 3.969), (52.0, 3.921), (53.0, 3.831), (54.0, 3.679), (55.0, 3.507), (56.0, 3.302), (57.0, 3.044), (58.0, 2.756), (59.0, 
2.457), (60.0, 2.159), (61.0, 1.853), (62.0, 1.561), (63.0, 1.291), (64.0, 1.055), (65.0, 0.859), (66.0, 0.699), (67.0, 0.569), (68.0, 0.465), (69.0, 0.384), (70.0, 0.321), (71.0, 
0.271), (72.0, 0.235), (73.0, 0.205), (74.0, 0.179), (75.0, 0.158), (76.0, 0.138), (77.0, 0.119), (78.0, 0.1), (79.0, 0.083), (80.0, 0.07), (81.0, 0.056), (82.0, 0.043), (83.0, 
0.033), (84.0, 0.025), (85.0, 0.018), (86.0, 0.013), (87.0, 0.009), (88.0, 0.006), (89.0, 0.004), (90.0, 0.002), (91.0, 0.001), (92.0, 0.001), (93.0, 0.0), (94.0, 0.0), (95.0, 0.0), 
(96.0, 0.0), (97.0, 0.0), (98.0, 0.0), (99.0, 0.0), (100.0, 0.0)] color='black' width=2 dash='dash' showlegend=False marker=None
name='Theoretical GC Content' pairs=[(0.0, 0.0), (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0), (5.0, 0.0), (6.0, 0.0), (7.0, 0.0), (8.0, 0.0), (9.0, 255.071895), (10.0, 255.071895),
(11.0, 255.071895), (12.0, 510.14379), (13.0, 765.215685), (14.0, 1275.359475), (15.0, 2040.57516), (16.0, 3315.9346349999996), (17.0, 5611.581689999999), (18.0, 9182.58822), (19.0, 
14028.954225000001), (20.0, 20915.895389999998), (21.0, 30098.483609999996), (22.0, 41831.790779999996), (23.0, 55605.67311), (24.0, 72185.34628499999), (25.0, 91315.73840999999), 
(26.0, 112741.77759000001), (27.0, 134933.032455), (28.0, 161460.509535), (29.0, 188243.05851), (30.0, 217831.39832999997), (31.0, 248950.16952), (32.0, 282874.731555), (33.0, 
320370.30011999997), (34.0, 360416.587635), (35.0, 404033.88168), (36.0, 449181.60709500004), (37.0, 495349.62009), (38.0, 544578.495825), (39.0, 593297.22777), (40.0, 642781.1754), 
(41.0, 693285.41061), (42.0, 746085.2928749999), (43.0, 798885.1751400001), (44.0, 850154.626035), (45.0, 895302.35145), (46.0, 937644.28602), (47.0, 969528.2728950001), (48.0, 
995800.67808), (49.0, 1011360.063675), (50.0, 1019777.4362100001), (51.0, 1012380.3512549999), (52.0, 1000136.9002949998), (53.0, 977180.429745), (54.0, 938409.501705), (55.0, 
894537.1357650001), (56.0, 842247.39729), (57.0, 776438.8483800001), (58.0, 702978.1426199999), (59.0, 626711.646015), (60.0, 550700.2213049999), (61.0, 472648.221435), (62.0, 
398167.22809499997), (63.0, 329297.816445), (64.0, 269100.84922499995), (65.0, 219106.757805), (66.0, 178295.254605), (67.0, 145135.908255), (68.0, 118608.431175), (69.0, 
97947.60768), (70.0, 81878.078295), (71.0, 69124.48354500001), (72.0, 59941.89532499999), (73.0, 52289.73847499999), (74.0, 45657.869204999995), (75.0, 40301.35941), (76.0, 
35199.92151000001), (77.0, 30353.555504999997), (78.0, 25507.1895), (79.0, 21170.967285), (80.0, 17855.03265), (81.0, 14284.026120000002), (82.0, 10968.091484999999), (83.0, 
8417.372535), (84.0, 6376.797375), (85.0, 4591.29411), (86.0, 3315.9346349999996), (87.0, 2295.647055), (88.0, 1530.43137), (89.0, 1020.28758), (90.0, 510.14379), (91.0, 255.071895), 
(92.0, 255.071895), (93.0, 0.0), (94.0, 0.0), (95.0, 0.0), (96.0, 0.0), (97.0, 0.0), (98.0, 0.0), (99.0, 0.0), (100.0, 0.0)] color='black' width=2 dash='dash' showlegend=False 
marker=None
   rendering plots | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 39/39  
     write_results | Data        : QC_report_liver_data   (overwritten)
     write_results | Report      : QC_report_liver.html   (overwritten)
     write_results | Plots       : QC_report_liver_plots   (overwritten)
           multiqc | MultiQC complete
guidoh@localhost:/mnt/files/guido$


 



## reverting back to v1.25.2:
## WORKS!
$ pip install --user --upgrade --force-reinstall git+https://github.com/MultiQC/MultiQC.git@v1.25.2

guidoh@localhost:/mnt/files/guido$ multiqc ./data_out --filename QC_report_liver.html --title "QC report mouse liver samples" --export --force

/// MultiQC 🎄 v1.25.2

            config | Loading config settings from: multiqc_config.yaml
     update_config | Report title: QC report mouse liver samples
     version_check | MultiQC Version v1.26 now available!
       file_search | Search path: /mnt/files/guido/data_out
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 4430/4430  
            preseq | Found 36 reports
             rseqc | Found 36 read_distribution reports
             rseqc | Found 36 gene_body_coverage reports
             rseqc | Found 36 inner_distance reports
             rseqc | Found 36 read_duplication reports
             rseqc | Found 36 junction_annotation reports
             rseqc | Found 36 junction_saturation reports
             rseqc | Found 36 infer_experiment reports
             rseqc | Found 36 bam_stat reports
             rseqc | Found 36 tin reports
            picard | Found 36 InsertSizeMetrics reports
            picard | Found 36 MarkDuplicates reports
            picard | Found 36 RnaSeqMetrics reports
          samtools | Found 36 stats reports
          samtools | Found 36 flagstat reports
          samtools | Found 36 idxstats reports
            salmon | Found 36 meta reports
            salmon | Found 36 fragment length distributions
            salmon | Found 36 library format counts reports
              star | Found 36 reports and 36 gene count files
             fastp | Found 18 reports
            fastqc | Found 72 reports
     write_results | Rendering plots. Export plots to formats png, svg, pdf is requested, so it might take a while. To disable plot export, set `export_plots: false` in config, or remove the `--export-plots` command line flag
name='A perfect library where each read is unique' pairs=[(0, 0), (43.39652336, 2.453829535655662)] color='#000000' width=1 dash='dash' showlegend=False marker=None
name='Theoretical GC Content' pairs=[(0.0, 0.0), (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0), (5.0, 0.0), (6.0, 0.0), (7.0, 0.0), (8.0, 0.0), (9.0, 0.001), (10.0, 0.001), (11.0, 
0.001), (12.0, 0.002), (13.0, 0.003), (14.0, 0.005), (15.0, 0.008), (16.0, 0.013), (17.0, 0.022), (18.0, 0.036), (19.0, 0.055), (20.0, 0.082), (21.0, 0.118), (22.0, 0.164), (23.0, 
0.218), (24.0, 0.283), (25.0, 0.358), (26.0, 0.442), (27.0, 0.529), (28.0, 0.633), (29.0, 0.738), (30.0, 0.854), (31.0, 0.976), (32.0, 1.109), (33.0, 1.256), (34.0, 1.413), (35.0, 
1.584), (36.0, 1.761), (37.0, 1.942), (38.0, 2.135), (39.0, 2.326), (40.0, 2.52), (41.0, 2.718), (42.0, 2.925), (43.0, 3.132), (44.0, 3.333), (45.0, 3.51), (46.0, 3.676), (47.0, 
3.801), (48.0, 3.904), (49.0, 3.965), (50.0, 3.998), (51.0, 3.969), (52.0, 3.921), (53.0, 3.831), (54.0, 3.679), (55.0, 3.507), (56.0, 3.302), (57.0, 3.044), (58.0, 2.756), (59.0, 
2.457), (60.0, 2.159), (61.0, 1.853), (62.0, 1.561), (63.0, 1.291), (64.0, 1.055), (65.0, 0.859), (66.0, 0.699), (67.0, 0.569), (68.0, 0.465), (69.0, 0.384), (70.0, 0.321), (71.0, 
0.271), (72.0, 0.235), (73.0, 0.205), (74.0, 0.179), (75.0, 0.158), (76.0, 0.138), (77.0, 0.119), (78.0, 0.1), (79.0, 0.083), (80.0, 0.07), (81.0, 0.056), (82.0, 0.043), (83.0, 
0.033), (84.0, 0.025), (85.0, 0.018), (86.0, 0.013), (87.0, 0.009), (88.0, 0.006), (89.0, 0.004), (90.0, 0.002), (91.0, 0.001), (92.0, 0.001), (93.0, 0.0), (94.0, 0.0), (95.0, 0.0), 
(96.0, 0.0), (97.0, 0.0), (98.0, 0.0), (99.0, 0.0), (100.0, 0.0)] color='black' width=2 dash='dash' showlegend=False marker=None
name='Theoretical GC Content' pairs=[(0.0, 0.0), (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0), (5.0, 0.0), (6.0, 0.0), (7.0, 0.0), (8.0, 0.0), (9.0, 255.071895), (10.0, 255.071895),
(11.0, 255.071895), (12.0, 510.14379), (13.0, 765.215685), (14.0, 1275.359475), (15.0, 2040.57516), (16.0, 3315.9346349999996), (17.0, 5611.581689999999), (18.0, 9182.58822), (19.0, 
14028.954225000001), (20.0, 20915.895389999998), (21.0, 30098.483609999996), (22.0, 41831.790779999996), (23.0, 55605.67311), (24.0, 72185.34628499999), (25.0, 91315.73840999999), 
(26.0, 112741.77759000001), (27.0, 134933.032455), (28.0, 161460.509535), (29.0, 188243.05851), (30.0, 217831.39832999997), (31.0, 248950.16952), (32.0, 282874.731555), (33.0, 
320370.30011999997), (34.0, 360416.587635), (35.0, 404033.88168), (36.0, 449181.60709500004), (37.0, 495349.62009), (38.0, 544578.495825), (39.0, 593297.22777), (40.0, 642781.1754), 
(41.0, 693285.41061), (42.0, 746085.2928749999), (43.0, 798885.1751400001), (44.0, 850154.626035), (45.0, 895302.35145), (46.0, 937644.28602), (47.0, 969528.2728950001), (48.0, 
995800.67808), (49.0, 1011360.063675), (50.0, 1019777.4362100001), (51.0, 1012380.3512549999), (52.0, 1000136.9002949998), (53.0, 977180.429745), (54.0, 938409.501705), (55.0, 
894537.1357650001), (56.0, 842247.39729), (57.0, 776438.8483800001), (58.0, 702978.1426199999), (59.0, 626711.646015), (60.0, 550700.2213049999), (61.0, 472648.221435), (62.0, 
398167.22809499997), (63.0, 329297.816445), (64.0, 269100.84922499995), (65.0, 219106.757805), (66.0, 178295.254605), (67.0, 145135.908255), (68.0, 118608.431175), (69.0, 
97947.60768), (70.0, 81878.078295), (71.0, 69124.48354500001), (72.0, 59941.89532499999), (73.0, 52289.73847499999), (74.0, 45657.869204999995), (75.0, 40301.35941), (76.0, 
35199.92151000001), (77.0, 30353.555504999997), (78.0, 25507.1895), (79.0, 21170.967285), (80.0, 17855.03265), (81.0, 14284.026120000002), (82.0, 10968.091484999999), (83.0, 
8417.372535), (84.0, 6376.797375), (85.0, 4591.29411), (86.0, 3315.9346349999996), (87.0, 2295.647055), (88.0, 1530.43137), (89.0, 1020.28758), (90.0, 510.14379), (91.0, 255.071895), 
(92.0, 255.071895), (93.0, 0.0), (94.0, 0.0), (95.0, 0.0), (96.0, 0.0), (97.0, 0.0), (98.0, 0.0), (99.0, 0.0), (100.0, 0.0)] color='black' width=2 dash='dash' showlegend=False 
marker=None
   rendering plots | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 40/40  
     write_results | Data        : QC_report_liver_data   (overwritten)
     write_results | Report      : QC_report_liver.html   (overwritten)
     write_results | Plots       : QC_report_liver_plots   (overwritten)
           multiqc | MultiQC complete
guidoh@localhost:/mnt/files/guido$
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this bug! I'd look into fixing it ASAP, but I can't reproduce the issue with the files you attached:

<img width="610" alt="Screenshot 2025-01-03 at 13 59 57" src="https://github.com/user-attachments/assets/fda3d35a-65f0-41db-8faf-4faa415d47f8" />

Could you please double check the tarball?

**Comment by vladsavelyev** [comment]
This potentially fixes it https://github.com/MultiQC/MultiQC/pull/3038 but need reproducible data with multiqc_config.yaml  to confirm

**Comment by guidohooiveld** [comment]
Thanks for having a look at this so quickly!

Unfortunately the changes made (https://github.com/MultiQC/MultiQC/pull/3038) do not fix the issue.
(Since I am not very familiar with installing GitHub commits, could you please check I indeed installed the fix). ;)


Yet, the issue seems more complicated than initially thought.
Based on the error I assumed it was triggered by the particular file I uploaded, but when I run MultiQC on only these 3 files this goes fine (like you also observed). Again, when parsing all output files for all FASTq files it gives an error.

To reproduce the error I have attached a ZIP with (only) the `preseq` files for 8 FASTq files.  

Not using `multiqc_config.yaml` didn't help; the same error is reported. Still, for completeness I have also attached my config file.


[out_cleaned.zip](https://github.com/user-attachments/files/18300851/out_cleaned.zip)
[multiqc_config.zip](https://github.com/user-attachments/files/18300859/multiqc_config.zip)




```
## error
guidoh@localhost:/mnt/files/guido$ multiqc ./TEST --filename QC_report_liver.html --title "QC report mouse liver sample" --export --force

/// MultiQC 🍾 v1.27.dev0

     update_config | Report title: QC report mouse liver sample
       file_search | Search path: /mnt/files/guido/TEST
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 25/25  
            preseq | Found 8 reports
╭──────────────────────────────────────────────────────────────────── Oops! The 'preseq' MultiQC module broke... ─────────────────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                                                                                                     │
│ Please attach a file that triggers the error. The last file found was:                                                                                                              │
│ TEST/STAR_out_cleaned/HTMLNDRX2_105485-001-004_TACGGTCT-GCAATGGA_L001_fastp_cleaned/HTMLNDRX2_105485-001-004_TACGGTCT-GCAATGGA_L001_fastp_cleaned_Aligned.sortedByCoord.out.bam.lc_ │
│ extrap.txt                                                                                                                                                                          │
│                                                                                                                                                                                     │
│ Traceback (most recent call last):                                                                                                                                                  │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/core/exec_modules.py", line 68, in exec_modules                                                                    │
│     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = module_initializer()                                                                                         │
│                                                                        ~~~~~~~~~~~~~~~~~~^^                                                                                         │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/modules/preseq/preseq.py", line 133, in __init__                                                                   │
│     self._make_preseq_length_trimmed_plot(reads_data, False)                                                                                                                        │
│     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^                                                                                                                        │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/modules/preseq/preseq.py", line 145, in _make_preseq_length_trimmed_plot                                           │
│     d_cnts = {sn: _modify_raw_data(sample_data, is_basepairs) for sn, sample_data in data_raw.items()}                                                                              │
│                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                       │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/modules/preseq/preseq.py", line 312, in _modify_raw_data                                                           │
│     return {_modify_raw_val(x, is_basepairs): _modify_raw_val(y, is_basepairs) for x, y in sample_data.items()}                                                                     │
│                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^                                                                                                      │
│   File "/home/guidoh/.local/lib/python3.13/site-packages/multiqc/modules/preseq/preseq.py", line 319, in _modify_raw_val                                                            │
│     return float(val) * (config.base_count_multiplier if is_basepairs else config.read_count_multiplier)                                                                            │
│            ~~~~~^^^^^                                                                                                                                                               │
│ TypeError: float() argument must be a string or a real number, not 'NoneType'                                                                                                       │
│                                                                                                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
           multiqc | No analysis results found. Cleaning up…
guidoh@localhost:/mnt/files/guido$ 


```




```
## install commit 6a2b0d3 (??)
guidoh@localhost:/mnt/files/guido/Aisha$  pip install --user --upgrade --force-reinstall git+https://github.com/MultiQC/MultiQC.git@6a2b0d3
Collecting git+https://github.com/MultiQC/MultiQC.git@6a2b0d3
  Cloning https://github.com/MultiQC/MultiQC.git (to revision 6a2b0d3) to /tmp/pip-req-build-l4gww0s0
  Running command git clone --filter=blob:none --quiet https://github.com/MultiQC/MultiQC.git /tmp/pip-req-build-l4gww0s0
  WARNING: Did not find branch or tag '6a2b0d3', assuming revision or ref.
  Running command git checkout -q 6a2b0d3
  Resolved https://github.com/MultiQC/MultiQC.git to commit 6a2b0d3
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from multiqc==1.27.dev0)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting humanize (from multiqc==1.27.dev0)

<< snip >>
```

**Comment by vladsavelyev** [comment]
Thanks a lot for the new files, I was able to reproduce it! 

Pushed a fix into the same PR https://github.com/MultiQC/MultiQC/pull/3038 and now it works 👍

**Comment by guidohooiveld** [comment]
Yep; I confirm it is working now! Thanks a lot for your prompt action.

The warning on the `FASTp` output is still there. I will open a new issue for this.
